/* Copyright(C) 2013, GaInOS-TK by Fan Wang. All rights reserved.
 * Generated by GaInOS-TK Studio at 2013-06-25:20-58-02.
 * Don't Modify it by hand.
 * Email: parai@foxmail.com
 * URL: https://github.com/parai/gainos-tk  && http://hi.baidu.com/parai
 */

#include "Os.h"
#include <stdio.h>

int g_counter = 0;
TASK(vTask0)
{
    /* Add your task special code here, but Don't delete this Task declaration.*/
    g_counter ++;
    (void)NextScheduleTable(vSchedTbl_0,vSchedTbl_1);
    (void)WaitEvent(0x01);
    (void)ClearEvent(0x01);
    printf("vTask0 is running.\r\n");
    (void)NextScheduleTable(vSchedTbl_1,vSchedTbl_0);
    (void)TerminateTask();
}

TASK(vTask1)
{
    /* Add your task special code here, but Don't delete this Task declaration.*/
    (void)WaitEvent(0x01);
    (void)ClearEvent(0x01);
    printf("vTask1 is running.\r\n");
    (void)TerminateTask();
}

TASK(vTask2)
{
    /* Add your task special code here, but Don't delete this Task declaration.*/
    (void)WaitEvent(0x01);
    (void)ClearEvent(0x01);
    printf("vTask2 is running.\r\n");
    (void)TerminateTask();
}

TASK(vTask3)
{
    /* Add your task special code here, but Don't delete this Task declaration.*/
    (void)WaitEvent(0x01);
    (void)ClearEvent(0x01);
    printf("vTask3 is running.\r\n");
    (void)TerminateTask();
}

TASK(vTask4)
{
    /* Add your task special code here, but Don't delete this Task declaration.*/
    (void)WaitEvent(0x01);
    (void)ClearEvent(0x01);
    printf("vTask4 is running.\r\n");
    (void)TerminateTask();
}

TASK(vTask5)
{
    /* Add your task special code here, but Don't delete this Task declaration.*/
    (void)WaitEvent(0x01);
    (void)ClearEvent(0x01);
    printf("vTask5 is running.\r\n");
    (void)TerminateTask();
}

TASK(vTaskStart)
{
    /* Add your task special code here, but Don't delete this Task declaration.*/
    printf("vTaskStart is running.\r\n");
    //(void)StartScheduleTableRel(vSchedTbl_0,50);
    //(void)StartScheduleTableRel(vSchedTbl_1,100);
    //while(g_counter < 2);
    //(void)StopScheduleTable(vSchedTbl_1);
    StartScheduleTableSynchron(vSchedTbl_0);
    SyncScheduleTable(vSchedTbl_0,50);
    (void)TerminateTask();
}

//---------------------------
LOCAL char* l_error_name_table[] = 
{
    "E_OK",
    "E_OS_ACCESS",
    "E_OS_CALLEVEL",
    "E_OS_ID",
    "E_OS_LIMIT",
    "E_OS_NOFUNC",
    "E_OS_RESOURCE",
    "E_OS_STATE",
    "E_OS_VALUE",
};
LOCAL char* l_service_id_name_table[] =
{
    "ActivateTask",
    "TerminateTask",
    "ChainTask",
    "Schedule",
    "GetTaskID",
    "GetTaskState",
    "GetAlarmBase",
    "GetAlarm",
    "SetRelAlarm",
    "SetAbsAlarm",
    "CancelAlarm",
    "SetEvent",
    "ClearEvent",
    "GetEvent",
    "WaitEvent",
    "GetResource",
    "ReleaseResource",
    "StartOS",
    "ShutdownOS",
};
void ErrorHook(StatusType Error)
{
    printf("%s : %s\r\n",l_error_name_table[Error],l_service_id_name_table[OSErrorGetServiceId()]);
}
