
/* Copyright(C) 2013, GaInOS-TK by Fan Wang. All rights reserved.
 * Generated by GaInOS-TK Studio at 2013-05-12:15-51-52. 
 * This is a template for "app.c", you can add your application code here.
 */
#include <stdio.h>
#include "Os.h"

TASK(vTaskInit)
{
    /* Add your task special code here, but Don't delete this Task declaration.*/
    printf("vTaskInit is running.\r\n");
    (void)TerminateTask();
}

TASK(vTaskSender)
{
    /* Add your task special code here, but Don't delete this Task declaration.*/
    printf("vTaskSender is running.\r\n");
    (void)TerminateTask();
}

TASK(vTaskReceiver)
{
    /* Add your task special code here, but Don't delete this Task declaration.*/
    printf("vTaskReceiver is running.\r\n");
    (void)TerminateTask();
}

TASK(vTaskMainFunction)
{
    /* Add your task special code here, but Don't delete this Task declaration.*/
    printf("vTaskMainFunction is running.\r\n");
    (void)TerminateTask();
}

TASK(vTaskIdle)
{
    /* Add your task special code here, but Don't delete this Task declaration.*/
    printf("vTaskIdle is running.\r\n");
    (void)TerminateTask();
}

ALARM(vAlarmSender)
{
    /* Alarm Type: Task, you still can add your special code here.*/
    (void)ActivateTask(ID_vTaskSender);
}
ALARM(vAlarmReceiver)
{
    /* Alarm Type: Task, you still can add your special code here.*/
    (void)ActivateTask(ID_vTaskReceiver);
}
ALARM(vAlarmMainFunction)
{
    /* Alarm Type: Task, you still can add your special code here.*/
    (void)ActivateTask(ID_vTaskMainFunction);
}
