#ifndef CTEST_CFG_H_H
#define CTEST_CFG_H_H

#define ATTRIBUTES()

#define DISABLE 0
#define ENABLE  1

#define CT_SCHEDULING_Task1 CT_NON_PREEMPTIVE
//#define CT_SCHEDULING_Task1 CT_PREEMPTIVE

#define ISR_CATEGORY_3 ENABLE
#endif 

