/* Copyright(C) 2013, GaInOS-TK by Fan Wang. All rights reserved.
 * Generated by GaInOS-TK Studio at 2013-07-15:21-35-22.
 * Don't Modify it by hand.
 * Email: parai@foxmail.com
 * URL: https://github.com/parai/gainos-tk  && http://hi.baidu.com/parai
 */

#ifndef _AUTOSAR_CFG_H_
#define _AUTOSAR_CFG_H_

#define cfgAUTOSAR_SCHEDULE_TABLE_NUM 2

#define vSchedTbl_0 0
#define vSchedTbl_1 1

#endif /* _AUTOSAR_CFG_H_ */

