/* Copyright(C) 2013, GaInOS-TK by Fan Wang. All rights reserved.
 * Generated by GaInOS-TK Studio at 2013-07-18:20-05-12.
 * Don't Modify it by hand.
 * Email: parai@foxmail.com
 * URL: https://github.com/parai/gainos-tk  && http://hi.baidu.com/parai
 */

#ifndef _AUTOSAR_CFG_H_
#define _AUTOSAR_CFG_H_

#define cfgAR_SCHEDTBL_QUEUE_METHOD SCHEDTBL_IN_LOOP

#define cfgAR_SCHEDTBL_NUM 2

#define vSchedTbl_0 0
#define vSchedTbl_1 1

#endif /* _AUTOSAR_CFG_H_ */

