/* Copyright(C) 2013, GaInOS-TK by Fan Wang. All rights reserved.
 * Generated by GaInOS-TK Studio at 2013-07-15:21-35-22.
 * Don't Modify it by hand.
 * Email: parai@foxmail.com
 * URL: https://github.com/parai/gainos-tk  && http://hi.baidu.com/parai
 */

#include "autosar_os.h"

LOCAL void knl_schedule_table_dummy_action(void){ /* for final delay only */ }

LOCAL void vSchedTbl_0_ExpiryPoint0_Action(void)
{
	(void)ActivateTask(vTask1);
}
LOCAL void vSchedTbl_0_ExpiryPoint1_Action(void)
{
	(void)ActivateTask(vTask2);
}
LOCAL void vSchedTbl_0_ExpiryPoint2_Action(void)
{
	(void)ActivateTask(vTask3);
}
LOCAL void vSchedTbl_0_ExpiryPoint3_Action(void)
{
	(void)ActivateTask(vTask4);
}
LOCAL void vSchedTbl_0_ExpiryPoint4_Action(void)
{
	(void)ActivateTask(vTask5);
}
LOCAL const ScheduleTableExpiryPointType vSchedTbl_0_ExpiryPointList[] = 
{
	{ 100 , vSchedTbl_0_ExpiryPoint0_Action },
	{ 200 , vSchedTbl_0_ExpiryPoint1_Action },
	{ 300 , vSchedTbl_0_ExpiryPoint2_Action },
	{ 400 , vSchedTbl_0_ExpiryPoint3_Action },
	{ 500 , vSchedTbl_0_ExpiryPoint4_Action },
	{ 600 , knl_schedule_table_dummy_action }
};
LOCAL void vSchedTbl_1_ExpiryPoint0_Action(void)
{
	(void)SetEvent(vTask0,vTask0Event0);
}
LOCAL void vSchedTbl_1_ExpiryPoint1_Action(void)
{
	(void)SetEvent(vTask1,vTask1Event0);
}
LOCAL void vSchedTbl_1_ExpiryPoint2_Action(void)
{
	(void)SetEvent(vTask2,vTask2Event0);
}
LOCAL void vSchedTbl_1_ExpiryPoint3_Action(void)
{
	(void)SetEvent(vTask4,vTask4Event0);
}
LOCAL void vSchedTbl_1_ExpiryPoint4_Action(void)
{
	(void)SetEvent(vTask5,vTask5Event0);
}
LOCAL const ScheduleTableExpiryPointType vSchedTbl_1_ExpiryPointList[] = 
{
	{ 150 , vSchedTbl_1_ExpiryPoint0_Action },
	{ 250 , vSchedTbl_1_ExpiryPoint1_Action },
	{ 350 , vSchedTbl_1_ExpiryPoint2_Action },
	{ 450 , vSchedTbl_1_ExpiryPoint3_Action },
	{ 550 , vSchedTbl_1_ExpiryPoint4_Action },
	{ 650 , knl_schedule_table_dummy_action }
};
EXPORT const T_GSCHEDTBL knl_gschedtbl_table[] = 
{
	GenSchedTblInfo(vSchedTbl_0, SystemTimer, EXPLICIT, 6, TRUE),
	GenSchedTblInfo(vSchedTbl_1, SystemTimer, IMPLICIT, 6, TRUE),
};

