#ifndef CANNM_CFG_H_H
#define CANNM_CFG_H_H

#define CANNM_DEV_ERROR_DETECT				STD_ON
#define CANNM_VERSION_INFO_API				STD_ON
#define CANNM_PASSIVE_MODE_ENABLED			STD_OFF
#define CANNM_USER_DATA_ENABLED				STD_ON
#define CANNM_REMOTE_SLEEP_IND_ENABLED		STD_OFF	// Not supported
#define CANNM_BUS_SYNCHRONIZATION_ENABLED	STD_OFF	// Not supported
#define CANNM_BUS_LOAD_REDUCTION_ENABLED	STD_OFF	// Not supported
#define CANNM_NODE_ID_ENABLED				STD_ON
#define CANNM_NODE_DETECTION_ENABLED		STD_ON
#define CANNM_IMMEDIATE_RESTART_ENABLED		STD_OFF	// Not supported
#define CANNM_PDU_RX_INDICATION_ENABLED		STD_ON
#define CANNM_STATE_CHANGE_IND_ENABLED		STD_OFF	// Not supported
#define CANNM_COM_CONTROL_ENABLED			STD_OFF	// Not supported
#define CANNM_IMMEDIATE_TXCONF_ENABLED		STD_OFF	// Not supported
#define CANNM_REPEAT_MSG_IND_ENABLED		STD_OFF	// Not supported

#define CANNM_CHANNEL_COUNT 1

#define CANNM_CHANNEL0 0

extern const CanNm_ConfigType CanNm_Config;
#endif

