/* Copyright(C) 2013, GaInOS-TK by Fan Wang. All rights reserved.
 * Generated by GaInOS-TK Studio at 2013-06-23:11-16-39.
 * Don't Modify it by hand.
 * Email: parai@foxmail.com
 * URL: https://github.com/parai/gainos-tk  && http://hi.baidu.com/parai
 */

#include "ComM.h"
#include "Nm.h"
#include "CanSM.h"

const ComM_ChannelType ComM_Channels[] = 
{
	{//vComM_Channel_0
		/* BusType = */  COMM_BUS_TYPE_CAN,
		/* BusSMNetworkHandle = */  ,
		/* NmChannelHandle = */  vNm_Channel_0,
		/* NmVariant = */  COMM_NM_VARIANT_FULL,
		/* MainFunctionPeriod = */  4,
		/* LightTimeout = */  1000,
		/* Number = */  0
	},
};

const ComM_ChannelType* vComM_User_0_ChannleList[] = 
{
	&ComM_Channels[0],//vComM_Channel_0
};
const ComM_UserType ComM_Users[] =
{
	{//vComM_User_0
		/* ChannelList = */ vComM_User_0_ChannleList,
		/* ChannelCount = */ 1
	},
};

const ComM_ConfigType ComM_Cfg = 
{
    /* Channels = */ ComM_Channels,
    /* Users = */ ComM_Users
};

