/* Copyright(C) 2013, GaInOS-TK by Fan Wang. All rights reserved.
 * Generated by GaInOS-TK Studio at 2013-06-15:15-35-34.
 * Don't Modify it by hand.
 * Email: parai@foxmail.com
 * URL: https://github.com/parai/gainos-tk  && http://hi.baidu.com/parai
 */

#ifndef COMM_CFG_H_H_H
#define COMM_CFG_H_H_H

#define COMM_VERSION_INFO_API STD_ON
#define COMM_DEV_ERROR_DETECT STD_ON
#define COMM_NO_COM STD_OFF
#define COMM_MODE_LIMITATION_ENABLED STD_ON
#define COMM_T_MIN_FULL_COM_MODE_DURATION 1000

#define COMM_CHANNEL_COUNT 1
#define vComM_Channel_0 0

typedef enum
{
	vComM_User_0,
	COMM_USER_COUNT
}ComM_UserHandleType;

extern const ComM_ConfigType ComM_Cfg;

#endif /* COMM_CFG_H_H_H */

