/* Copyright(C) 2013, GaInOS-TK by Fan Wang. All rights reserved.
 * Generated by GaInOS-TK Studio at 2013-05-26:23-53-01.
 * Don't Modify it by hand.
 * Email: parai@foxmail.com
 * URL: https://github.com/parai/gainos-tk  && http://hi.baidu.com/parai
 */

#include "Std_Types.h"
#include "Dcm.h"
#if defined(USE_PDUR)
#include "PduR.h"
#endif

#define DCM_SECURITY_EOL_INDEX 2
#define DCM_SESSION_EOL_INDEX 2
#define DCM_DID_LIST_EOL_INDEX 2

extern Std_ReturnType vSecurityLevel_0_GetSeed (uint8 *securityAccessDataRecord, uint8 *seed, Dcm_NegativeResponseCodeType *errorCode);
extern Std_ReturnType vSecurityLevel_0_CompKey (uint8 *key);
extern Std_ReturnType vSecurityLevel_1_GetSeed (uint8 *securityAccessDataRecord, uint8 *seed, Dcm_NegativeResponseCodeType *errorCode);
extern Std_ReturnType vSecurityLevel_1_CompKey (uint8 *key);
extern Std_ReturnType vRequestService_0_Start (Dcm_ProtocolType protocolID);
extern Std_ReturnType vRequestService_0_Stop (Dcm_ProtocolType protocolID);

extern Std_ReturnType vRequestService_1_Start (Dcm_ProtocolType protocolID);
extern Std_ReturnType vRequestService_1_Stop (Dcm_ProtocolType protocolID);

const Dcm_DspSecurityRowType DspSecurityList[] = {
	{ // vSecurityLevel_0
		/* DspSecurityLevel = */ 0,
		/* DspSecurityDelayTimeOnBoot = */ 0,/* Value is not configurable */
		/* DspSecurityNumAttDelay = */ 0, 	/* Value is not configurable */
		/* DspSecurityDelayTime = */ 0, 	/* Value is not configurable */
		/* DspSecurityNumAttLock = */ 0, 	/* Value is not configurable */
		/* DspSecurityADRSize = */ 1,
		/* DspSecuritySeedSize = */ 1,
		/* DspSecurityKeySize = */ 1,
		/* GetSeed = */ vSecurityLevel_0_GetSeed,
		/* CompareKey = */ vSecurityLevel_0_CompKey,
		/* Arc_EOL = */ FALSE
	},
	{ // vSecurityLevel_1
		/* DspSecurityLevel = */ 1,
		/* DspSecurityDelayTimeOnBoot = */ 0,/* Value is not configurable */
		/* DspSecurityNumAttDelay = */ 0, 	/* Value is not configurable */
		/* DspSecurityDelayTime = */ 0, 	/* Value is not configurable */
		/* DspSecurityNumAttLock = */ 0, 	/* Value is not configurable */
		/* DspSecurityADRSize = */ 1,
		/* DspSecuritySeedSize = */ 1,
		/* DspSecurityKeySize = */ 1,
		/* GetSeed = */ vSecurityLevel_1_GetSeed,
		/* CompareKey = */ vSecurityLevel_1_CompKey,
		/* Arc_EOL = */ FALSE
	},
	{ // Dummy For EOL
		/* DspSecurityLevel = */ 0xBD,
		/* DspSecurityDelayTimeOnBoot = */ 0,/* Value is not configurable */
		/* DspSecurityNumAttDelay = */ 0, 	/* Value is not configurable */
		/* DspSecurityDelayTime = */ 0, 	/* Value is not configurable */
		/* DspSecurityNumAttLock = */ 0, 	/* Value is not configurable */
		/* DspSecurityADRSize = */ 0xBD,
		/* DspSecuritySeedSize = */ 0xBD,
		/* DspSecurityKeySize = */ 0xBD,
		/* GetSeed = */ NULL,
		/* CompareKey = */ NULL,
		/* Arc_EOL = */ TRUE
	}
};

const Dcm_DspSecurityType DspSecurity = {
    /* DspSecurityRow = */ DspSecurityList
};
const Dcm_DspSessionRowType DspSessionList[] = {
	{ //vSession_0
		/* DspSessionLevel = */ ???,
		/* DspSessionP2ServerMax = */ ???,
		/* DspSessionP2StarServerMax = */ ???,
		/* Arc_EOL = */ FALSE
	},
	{ //vSession_1
		/* DspSessionLevel = */ ???,
		/* DspSessionP2ServerMax = */ ???,
		/* DspSessionP2StarServerMax = */ ???,
		/* Arc_EOL = */ FALSE
	},
	{ //Dummy Session For EOL
		/* DspSessionLevel = */ ???,
		/* DspSessionP2ServerMax = */ ???,
		/* DspSessionP2StarServerMax = */ ???,
		/* Arc_EOL = */ TRUE
	},
};

const Dcm_DspSessionRowType *vServiceTable_0_vService0_SessionList[] = {
	&DspSessionList[0],//vSession_0
	&DspSessionList[DCM_SESSION_EOL_INDEX]
};
const Dcm_DspSessionRowType *vServiceTable_0_vService1_SessionList[] = {
	&DspSessionList[0],//vSession_0
	&DspSessionList[DCM_SESSION_EOL_INDEX]
};
const Dcm_DspSessionRowType *vServiceTable_1_vService0_SessionList[] = {
	&DspSessionList[1],//vSession_1
	&DspSessionList[DCM_SESSION_EOL_INDEX]
};
