/* Copyright(C) 2013, GaInOS-TK by Fan Wang. All rights reserved.
 * Generated by GaInOS-TK Studio at 2013-05-27:23-59-38.
 * Don't Modify it by hand.
 * Email: parai@foxmail.com
 * URL: https://github.com/parai/gainos-tk  && http://hi.baidu.com/parai
 */

#include "Std_Types.h"
#include "Dcm.h"
#if defined(USE_PDUR)
#include "PduR.h"
#endif

#define DCM_SECURITY_EOL_INDEX 2
#define DCM_SESSION_EOL_INDEX 2
#define DCM_DID_LIST_EOL_INDEX 2

extern Std_ReturnType vSecurityLevel_0_GetSeed (uint8 *securityAccessDataRecord, uint8 *seed, Dcm_NegativeResponseCodeType *errorCode);
extern Std_ReturnType vSecurityLevel_0_CompKey (uint8 *key);
extern Std_ReturnType vSecurityLevel_1_GetSeed (uint8 *securityAccessDataRecord, uint8 *seed, Dcm_NegativeResponseCodeType *errorCode);
extern Std_ReturnType vSecurityLevel_1_CompKey (uint8 *key);
extern Std_ReturnType vRequestService_0_Start (Dcm_ProtocolType protocolID);
extern Std_ReturnType vRequestService_0_Stop (Dcm_ProtocolType protocolID);

extern Std_ReturnType vRequestService_1_Start (Dcm_ProtocolType protocolID);
extern Std_ReturnType vRequestService_1_Stop (Dcm_ProtocolType protocolID);

const Dcm_DspSecurityRowType DspSecurityList[] = {
	{ // vSecurityLevel_0
		/* DspSecurityLevel = */ 0,
		/* DspSecurityDelayTimeOnBoot = */ 0,/* Value is not configurable */
		/* DspSecurityNumAttDelay = */ 0, 	/* Value is not configurable */
		/* DspSecurityDelayTime = */ 0, 	/* Value is not configurable */
		/* DspSecurityNumAttLock = */ 0, 	/* Value is not configurable */
		/* DspSecurityADRSize = */ 1,
		/* DspSecuritySeedSize = */ 1,
		/* DspSecurityKeySize = */ 1,
		/* GetSeed = */ vSecurityLevel_0_GetSeed,
		/* CompareKey = */ vSecurityLevel_0_CompKey,
		/* Arc_EOL = */ FALSE
	},
	{ // vSecurityLevel_1
		/* DspSecurityLevel = */ 1,
		/* DspSecurityDelayTimeOnBoot = */ 0,/* Value is not configurable */
		/* DspSecurityNumAttDelay = */ 0, 	/* Value is not configurable */
		/* DspSecurityDelayTime = */ 0, 	/* Value is not configurable */
		/* DspSecurityNumAttLock = */ 0, 	/* Value is not configurable */
		/* DspSecurityADRSize = */ 1,
		/* DspSecuritySeedSize = */ 1,
		/* DspSecurityKeySize = */ 1,
		/* GetSeed = */ vSecurityLevel_1_GetSeed,
		/* CompareKey = */ vSecurityLevel_1_CompKey,
		/* Arc_EOL = */ FALSE
	},
	{ // Dummy For EOL
		/* DspSecurityLevel = */ 0xBD,
		/* DspSecurityDelayTimeOnBoot = */ 0,/* Value is not configurable */
		/* DspSecurityNumAttDelay = */ 0, 	/* Value is not configurable */
		/* DspSecurityDelayTime = */ 0, 	/* Value is not configurable */
		/* DspSecurityNumAttLock = */ 0, 	/* Value is not configurable */
		/* DspSecurityADRSize = */ 0xBD,
		/* DspSecuritySeedSize = */ 0xBD,
		/* DspSecurityKeySize = */ 0xBD,
		/* GetSeed = */ NULL,
		/* CompareKey = */ NULL,
		/* Arc_EOL = */ TRUE
	}
};

const Dcm_DspSecurityType DspSecurity = {
    /* DspSecurityRow = */ DspSecurityList
};
const Dcm_DspSessionRowType DspSessionList[] = {
	{ //vSession_0
		/* DspSessionLevel = */ 0,
		/* DspSessionP2ServerMax = */ 10,
		/* DspSessionP2StarServerMax = */ 10,
		/* Arc_EOL = */ FALSE
	},
	{ //vSession_1
		/* DspSessionLevel = */ 1,
		/* DspSessionP2ServerMax = */ 10,
		/* DspSessionP2StarServerMax = */ 10,
		/* Arc_EOL = */ FALSE
	},
	{ //Dummy Session For EOL
		/* DspSessionLevel = */ 0xBD,
		/* DspSessionP2ServerMax = */ 0xBD,
		/* DspSessionP2StarServerMax = */ 0xBD,
		/* Arc_EOL = */ TRUE
	},
};

const Dcm_DspSessionType DspSession = {
    /* DspSessionRow = */ DspSessionList,
};

const Dcm_DspSecurityRowType *vServiceTable_0_vService0_SecurityList[] = {
	&DspSecurityList[0],//vSecurityLevel_0
	&DspSecurityList[DCM_SECURITY_EOL_INDEX]
};
const Dcm_DspSecurityRowType *vServiceTable_0_vService1_SecurityList[] = {
	&DspSecurityList[0],//vSecurityLevel_0
	&DspSecurityList[DCM_SECURITY_EOL_INDEX]
};
const Dcm_DspSecurityRowType *vServiceTable_1_vService0_SecurityList[] = {
	&DspSecurityList[1],//vSecurityLevel_1
	&DspSecurityList[DCM_SECURITY_EOL_INDEX]
};
const Dcm_DspSessionRowType *vServiceTable_0_vService0_SessionList[] = {
	&DspSessionList[0],//vSession_0
	&DspSessionList[DCM_SESSION_EOL_INDEX]
};
const Dcm_DspSessionRowType *vServiceTable_0_vService1_SessionList[] = {
	&DspSessionList[0],//vSession_0
	&DspSessionList[DCM_SESSION_EOL_INDEX]
};
const Dcm_DspSessionRowType *vServiceTable_1_vService0_SessionList[] = {
	&DspSessionList[1],//vSession_1
	&DspSessionList[DCM_SESSION_EOL_INDEX]
};

const Dcm_DspSessionRowType *vDcmDidInfo_0_read_sessionRefList[] = {
	&DspSessionList[0],//vSession_0
	&DspSessionList[DCM_SESSION_EOL_INDEX]
};
const Dcm_DspSecurityRowType *vDcmDidInfo_0_read_securityRefList[] = {
	&DspSecurityList[0],//vSecurityLevel_0
	&DspSecurityList[DCM_SECURITY_EOL_INDEX]
};
const Dcm_DspDidReadType vDcmDidInfo_0_didRead = {
    /* DspDidReadSessionRef = */ vDcmDidInfo_0_read_sessionRefList,
    /* DspDidReadSecurityLevelRef = */ vDcmDidInfo_0_read_securityRefList
};

const Dcm_DspSessionRowType *vDcmDidInfo_0_write_sessionRefList[] = {
	&DspSessionList[0],//vSession_0
	&DspSessionList[DCM_SESSION_EOL_INDEX]
};
const Dcm_DspSecurityRowType *vDcmDidInfo_0_write_securityRefList[] = {
	&DspSecurityList[0],//vSecurityLevel_0
	&DspSecurityList[DCM_SECURITY_EOL_INDEX]
};
const Dcm_DspDidWriteType vDcmDidInfo_0_didWrite = {
    /* DspDidReadSessionRef = */ vDcmDidInfo_0_write_sessionRefList,
    /* DspDidReadSecurityLevelRef = */ vDcmDidInfo_0_write_securityRefList
};

const Dcm_DspSessionRowType *vDcmDidInfo_0_control_sessionRefList[] = {
	&DspSessionList[0],//vSession_0
	&DspSessionList[DCM_SESSION_EOL_INDEX]
};
const Dcm_DspSecurityRowType *vDcmDidInfo_0_control_securityRefList[] = {
	&DspSecurityList[0],//vSecurityLevel_0
	&DspSecurityList[DCM_SECURITY_EOL_INDEX]
};
const Dcm_DspDidControlType vDcmDidInfo_0_didControl = {
    /* DspDidReadSessionRef = */ vDcmDidInfo_0_control_sessionRefList,
    /* DspDidReadSecurityLevelRef = */ vDcmDidInfo_0_control_securityRefList,
    /* DspDidFreezeCurrentState = */ NULL,
    /* DspDidResetToDefault = */ NULL,
    /* DspDidReturnControlToEcu = */ NULL,
    /* DspDidShortTermAdjustment = */ NULL
};

const Dcm_DspSessionRowType *vDcmDidInfo_1_read_sessionRefList[] = {
	&DspSessionList[1],//vSession_1
	&DspSessionList[DCM_SESSION_EOL_INDEX]
};
const Dcm_DspSecurityRowType *vDcmDidInfo_1_read_securityRefList[] = {
	&DspSecurityList[1],//vSecurityLevel_1
	&DspSecurityList[DCM_SECURITY_EOL_INDEX]
};
const Dcm_DspDidReadType vDcmDidInfo_1_didRead = {
    /* DspDidReadSessionRef = */ vDcmDidInfo_1_read_sessionRefList,
    /* DspDidReadSecurityLevelRef = */ vDcmDidInfo_1_read_securityRefList
};

const Dcm_DspSessionRowType *vDcmDidInfo_1_write_sessionRefList[] = {
	&DspSessionList[1],//vSession_1
	&DspSessionList[DCM_SESSION_EOL_INDEX]
};
const Dcm_DspSecurityRowType *vDcmDidInfo_1_write_securityRefList[] = {
	&DspSecurityList[1],//vSecurityLevel_1
	&DspSecurityList[DCM_SECURITY_EOL_INDEX]
};
const Dcm_DspDidWriteType vDcmDidInfo_1_didWrite = {
    /* DspDidReadSessionRef = */ vDcmDidInfo_1_write_sessionRefList,
    /* DspDidReadSecurityLevelRef = */ vDcmDidInfo_1_write_securityRefList
};

const Dcm_DspSessionRowType *vDcmDidInfo_1_control_sessionRefList[] = {
	&DspSessionList[1],//vSession_1
	&DspSessionList[DCM_SESSION_EOL_INDEX]
};
const Dcm_DspSecurityRowType *vDcmDidInfo_1_control_securityRefList[] = {
	&DspSecurityList[1],//vSecurityLevel_1
	&DspSecurityList[DCM_SECURITY_EOL_INDEX]
};
const Dcm_DspDidControlType vDcmDidInfo_1_didControl = {
    /* DspDidReadSessionRef = */ vDcmDidInfo_1_control_sessionRefList,
    /* DspDidReadSecurityLevelRef = */ vDcmDidInfo_1_control_securityRefList,
    /* DspDidFreezeCurrentState = */ NULL,
    /* DspDidResetToDefault = */ NULL,
    /* DspDidReturnControlToEcu = */ NULL,
    /* DspDidShortTermAdjustment = */ NULL
};

const Dcm_DspDidInfoType DspDidInfoList[] = {
	{ // vDcmDidInfo_0
		 /* DspDidDynamicllyDefined = */ FALSE,
		 /* DspDidFixedLength = */ TRUE,
		 /* DspDidScalingInfoSize = */ 8,
		{ // DspDidAccess
			 /* DspDidRead */ vDcmDidInfo_0_didRead,
			 /* DspDidWrite */ vDcmDidInfo_0_didWrite,
			 /* DspDidControl */ vDcmDidInfo_0_didControl,
		}
	}, 
	{ // vDcmDidInfo_1
		 /* DspDidDynamicllyDefined = */ FALSE,
		 /* DspDidFixedLength = */ TRUE,
		 /* DspDidScalingInfoSize = */ 8,
		{ // DspDidAccess
			 /* DspDidRead */ vDcmDidInfo_1_didRead,
			 /* DspDidWrite */ vDcmDidInfo_1_didWrite,
			 /* DspDidControl */ vDcmDidInfo_1_didControl,
		}
	}, 
};

const Dcm_DspDidType DspDidList[] = { 
	{ // vDid_0,
		/* DspDidUsePort = */ FALSE,/* Value is not configurable */
		/* DspDidIdentifier = */ 0x0,
		/* DspDidInfoRef = */ &DspDidInfoList[0], //vDcmDidInfo_0
		/* DspDidRef = */ NULL, //I cann't understand
		/* DspDidSize = */ 64,
		/* DspDidReadDataLengthFnc = */ NULL,
        /* DspDidConditionCheckReadFnc = */ NULL,
        /* DspDidReadDataFnc = */ NULL,
        /* DspDidConditionCheckWriteFnc = */ NULL,
        /* DspDidWriteDataFnc = */ NULL,
        /* DspDidGetScalingInfoFnc = */ NULL,
        /* DspDidFreezeCurrentStateFnc = */ NULL,	
        /* DspDidResetToDefaultFnc = */ NULL,
        /* DspDidReturnControlToEcuFnc = */ NULL,
        /* DspDidShortTermAdjustmentFnc = */ NULL,
        /* DspDidControlRecordSize = */ NULL,
		/* Arc_EOL = */ FALSE
	},
	{ // vDid_1,
		/* DspDidUsePort = */ FALSE,/* Value is not configurable */
		/* DspDidIdentifier = */ 0x1,
		/* DspDidInfoRef = */ &DspDidInfoList[1], //vDcmDidInfo_1
		/* DspDidRef = */ NULL, //I cann't understand
		/* DspDidSize = */ 64,
		/* DspDidReadDataLengthFnc = */ NULL,
        /* DspDidConditionCheckReadFnc = */ NULL,
        /* DspDidReadDataFnc = */ NULL,
        /* DspDidConditionCheckWriteFnc = */ NULL,
        /* DspDidWriteDataFnc = */ NULL,
        /* DspDidGetScalingInfoFnc = */ NULL,
        /* DspDidFreezeCurrentStateFnc = */ NULL,	
        /* DspDidResetToDefaultFnc = */ NULL,
        /* DspDidReturnControlToEcuFnc = */ NULL,
        /* DspDidShortTermAdjustmentFnc = */ NULL,
        /* DspDidControlRecordSize = */ NULL,
		/* Arc_EOL = */ FALSE
	},
	{ // Dummy for EOL,
		/* DspDidUsePort = */ FALSE,/* Value is not configurable */
		/* DspDidIdentifier = */ 0xDB,
		/* DspDidInfoRef = */ NULL,
		/* DspDidRef = */ NULL, //I cann't understand
		/* DspDidSize = */ 0xDB,
		/* DspDidReadDataLengthFnc = */ NULL,
        /* DspDidConditionCheckReadFnc = */ NULL,
        /* DspDidReadDataFnc = */ NULL,
        /* DspDidConditionCheckWriteFnc = */ NULL,
        /* DspDidWriteDataFnc = */ NULL,
        /* DspDidGetScalingInfoFnc = */ NULL,
        /* DspDidFreezeCurrentStateFnc = */ NULL,	
        /* DspDidResetToDefaultFnc = */ NULL,
        /* DspDidReturnControlToEcuFnc = */ NULL,
        /* DspDidShortTermAdjustmentFnc = */ NULL,
        /* DspDidControlRecordSize = */ NULL,
		/* Arc_EOL = */ TRUE
	}
};

/************************************************************************
 *							Routine control								*
 ************************************************************************/

/************************************************************************
 *							Memory Info             					*
 ************************************************************************/

const Dcm_DspType Dsp = {
    /* DspMaxDidToRead = */ 0x99,//????
    /* DspDid = */ DspDidList,
    /* DspDidInfo = */ DspDidInfoList,
    /* DspEcuReset = */ NULL,
    /* DspPid = */ NULL,
    /* DspReadDTC = */ NULL,
    /* DspRequestControl = */ NULL,
    /* DspRoutine = */ NULL,//DspRoutineList,???
    /* DspRoutineInfo = */ NULL,//DspRoutineInfoList,???
    /* DspSecurity = */ &DspSecurity,
    /* DspSession = */ &DspSession,
    /* DspTestResultByObdmid = */ NULL,
    /* DspVehInfo = */ NULL
};

/************************************************************************
 *									DSD									*
 ************************************************************************/

const Dcm_DsdServiceType vServiceTable_0_serviceList[] = {
	{ // vService0
		 /* DsdSidTabServiceId =*/ SID_DIAGNOSTIC_SESSION_CONTROL,
		 /* DsdSidTabSubfuncAvail =*/ FALSE,
		 /* DsdSidTabSecurityLevelRef =*/ vServiceTable_0_vService0_SecurityList,
		 /* DsdSidTabSessionLevelRef =*/ vServiceTable_0_vService0_SessionList,
		 /* Arc_EOL = */ FALSE
	},
	{ // vService1
		 /* DsdSidTabServiceId =*/ SID_ECU_RESET,
		 /* DsdSidTabSubfuncAvail =*/ FALSE,
		 /* DsdSidTabSecurityLevelRef =*/ vServiceTable_0_vService1_SecurityList,
		 /* DsdSidTabSessionLevelRef =*/ vServiceTable_0_vService1_SessionList,
		 /* Arc_EOL = */ FALSE
	},
	{ // Dummy For EOL
		 /* DsdSidTabServiceId =*/ 0xDB,
		 /* DsdSidTabSubfuncAvail =*/ FALSE,
		 /* DsdSidTabSecurityLevelRef =*/ NULL,
		 /* DsdSidTabSessionLevelRef =*/ NULL,
		 /* Arc_EOL = */ TRUE
	}
};

const Dcm_DsdServiceType vServiceTable_1_serviceList[] = {
	{ // vService0
		 /* DsdSidTabServiceId =*/ SID_READ_DTC_INFORMATION,
		 /* DsdSidTabSubfuncAvail =*/ FALSE,
		 /* DsdSidTabSecurityLevelRef =*/ vServiceTable_1_vService0_SecurityList,
		 /* DsdSidTabSessionLevelRef =*/ vServiceTable_1_vService0_SessionList,
		 /* Arc_EOL = */ FALSE
	},
	{ // Dummy For EOL
		 /* DsdSidTabServiceId =*/ 0xDB,
		 /* DsdSidTabSubfuncAvail =*/ FALSE,
		 /* DsdSidTabSecurityLevelRef =*/ NULL,
		 /* DsdSidTabSessionLevelRef =*/ NULL,
		 /* Arc_EOL = */ TRUE
	}
};

const Dcm_DsdServiceTableType DsdServiceTable[] = {	
	{ // vServiceTable_0
		 /* DsdSidTabId = */ 0,
		 /* DsdService = */ vServiceTable_0_serviceList,
		 /* Arc_EOL = */ FALSE
	},
	{ // vServiceTable_1
		 /* DsdSidTabId = */ 1,
		 /* DsdService = */ vServiceTable_1_serviceList,
		 /* Arc_EOL = */ FALSE
	},
	{ // Dummy For EOL 
		 /* DsdSidTabId = */ 0xDB,
		 /* DsdService = */ NULL,
		 /* Arc_EOL = */ TRUE
	}
};

const Dcm_DsdType Dsd = {
    /* DsdServiceTable = */ DsdServiceTable
};

/************************************************************************
 *									DSL									*
 ************************************************************************/

