/*
* Configuration of module: J1939Tp (J1939Tp_LCfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    HCS12
*
* Module vendor:           ArcCore
* Generator version:       1.0.7
*
* Generated by Arctic Studio (http://arccore.com) 
*/

	

#include "J1939Tp.h"
#include "CanIf.h"
#include "PduR.h"

#if 0
const J1939Tp_PgType Pgs[J1939TP_PG_COUNT];

const J1939Tp_PgType* TxChannel1_Pgs[TXCHANNEL1_PG_COUNT] = {
	&(Pgs[0]),
};
const J1939Tp_PgType* RxChannel1_Pgs[RXCHANNEL1_PG_COUNT] = {
	&(Pgs[1]),
};


const J1939Tp_ChannelType Channels[J1939TP_CHANNEL_COUNT] = {
		{	/* TxChannel1 */
			.Protocol = J1939TP_PROTOCOL_CMDT,
			.FcNPdu = CANIF_PDU_ID_PDU_0_RX,
			.CmNPdu = CANIF_PDU_ID_PDU_0_TX,
			.DtNPdu = CANIF_PDU_ID_PDU_0_RX,
			.Direction = J1939TP_TX,
			.Pgs = TxChannel1_Pgs,
			.PgCount = TXCHANNEL1_PG_COUNT
		},
		{	/* RxChannel1 */
			.Protocol = J1939TP_PROTOCOL_BAM,
			.FcNPdu = -1,
			.CmNPdu = CANIF_PDU_ID_PDU_0_RX,
			.DtNPdu = CANIF_PDU_ID_PDU_0_TX,
			.Direction = J1939TP_RX,
			.Pgs = RxChannel1_Pgs,
			.PgCount = RXCHANNEL1_PG_COUNT
		},
};

const J1939Tp_PgType Pgs[J1939TP_PG_COUNT] = {
		{	//PG: TxPg
			.Pgn = 0,			
			.DirectNPdu = CANIF_PDU_ID_PDU_2,			
			.NSdu = PDUR_PDU_ID_PDU_1,
			.Channel = &Channels[0] /* parent channel */
		},
		{	//PG: RxPg
			.Pgn = 0,			
			.DirectNPdu = CANIF_PDU_ID_PDU_0_TX,			
			.NSdu = PDUR_PDU_ID_PDU_1_RX,
			.Channel = &Channels[1] /* parent channel */
		},
};

const J1939Tp_RxPduInfoType RxPdus[J1939TP_RX_PDU_COUNT] = {
	{
		.PacketType = J1939TP_CM,
		.ChannelIndex = 0,
		.PgPtr = 0, 
	},
	{
		.PacketType = J1939TP_DT,
		.ChannelIndex = 0,
		.PgPtr = 0, 
	},
	{
		.PacketType = J1939TP_REVERSE_CM,
		.ChannelIndex = 0,
		.PgPtr = 0, 
	},
	{
		.PacketType = J1939TP_DIRECT,
		.ChannelIndex = 0,
		.PgPtr = &(Pgs[0]), 
	},
	{
		.PacketType = J1939TP_CM,
		.ChannelIndex = 1,
		.PgPtr = 0, 
	},
	{
		.PacketType = J1939TP_DT,
		.ChannelIndex = 1,
		.PgPtr = 0, 
	},
	{
		.PacketType = J1939TP_DIRECT,
		.ChannelIndex = 1,
		.PgPtr = &(Pgs[1]), 
	},
};

const J1939Tp_RxPduInfoType* RxPduRelations_PDU_0_TX[] = {
		&RxPdus[0],
		&RxPdus[5],
		&RxPdus[6],		
};
const J1939Tp_RxPduInfoType* RxPduRelations_PDU_2[] = {
		&RxPdus[3],		
};
const J1939Tp_RxPduInfoType* RxPduRelations_PDU_0_RX[] = {
		&RxPdus[1],
		&RxPdus[2],
		&RxPdus[4],		
};

const J1939Tp_RxPduInfoRelationsType RxPduRelations[J1939TP_RX_PDU_COUNT] = {
	{
		.RxPdus = RxPduRelations_PDU_0_TX,
		.RxPduCount = 3,
	},
	{
		.RxPdus = RxPduRelations_PDU_2,
		.RxPduCount = 1,
	},
	{
		.RxPdus = RxPduRelations_PDU_0_RX,
		.RxPduCount = 3,
	},
};
#endif
const J1939Tp_ConfigType J1939Tp_Config = {
	/* .Pgs = */ NULL,//Pgs,
	//.RxPduRelations = RxPduRelations,
	//.Channels = Channels,
};

