/*
* Configuration of module: J1939Tp (J1939Tp_Cfg.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    HCS12
*
* Module vendor:           ArcCore
* Generator version:       1.0.7
*
* Generated by Arctic Studio (http://arccore.com) 
*/


#if !(((J1939TP_SW_MAJOR_VERSION == 1) && (J1939TP_SW_MINOR_VERSION == 0)) )
#error J1939Tp: Configuration file expected BSW module version to be 1.0.*
#endif

	

#ifndef J1939TP_CFG_H
#define J1939TP_CFG_H

#include "J1939Tp.h"

#define J1939TP_DEV_ERROR_DETECT 		STD_OFF
#define J1939TP_PACKETS_PER_BLOCK		0
#define J1939TP_MAIN_FUNCTION_PERIOD 	0
#define J1939TP_TX_CONF_TIMEOUT			0

#define J1939TP_CHANNEL_COUNT 		2
#define J1939TP_TX_CHANNEL_COUNT 	1
#define J1939TP_RX_CHANNEL_COUNT 	1

#define J1939TP_RX_PDU_COUNT 	7

#define J1939TP_PG_COUNT 		2
#define J1939TP_TX_PG_COUNT 	1
#define J1939TP_RX_PG_COUNT 	1

// Number of pgs for each channel 
#define TXCHANNEL1_PG_COUNT		1
#define RXCHANNEL1_PG_COUNT		1


// NSDU:s
#define J1939TP_PDU_ID_PDU_1		0
#define J1939TP_PDU_ID_PDU_1_RX		1

// PDU:S
#define J1939TP_PDU_ID_PDU_0_TX		0
#define J1939TP_PDU_ID_PDU_2		1
#define J1939TP_PDU_ID_PDU_0_RX		2


extern const J1939Tp_ConfigType J1939Tp_Config;

#endif /*J1939TP_CFG_H*/