/* Copyright(C) 2013, GaInOS-TK by Fan Wang. All rights reserved.
 * Generated by GaInOS-TK Studio at 2013-06-17:11-29-51.
 * Don't Modify it by hand.
 * Email: parai@foxmail.com
 * URL: https://github.com/parai/gainos-tk  && http://hi.baidu.com/parai
 */

#ifndef NM_CFG_H_H
#define NM_CFG_H_H

#define NM_DEV_ERROR_DETECT STD_ON
#define NM_VERSION_INFO_API STD_ON
#define NM_USER_DATA_ENABLED STD_ON
#define NM_NODE_ID_ENABLED STD_ON
#define NM_NODE_DETECTION_ENABLED STD_ON

#define vNm_Channel_0 0

#define USE_CANNM

extern const Nm_ConfigType Nm_Config;

#endif /* NM_CFG_H_H */

