# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\parai@foxmail.com\github\gainos-tk\tool\gainos-studio\ui\forms\cd_com.ui'
#
# Created: Tue May 14 19:56:47 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_cd_com(object):
    def setupUi(self, cd_com):
        cd_com.setObjectName(_fromUtf8("cd_com"))
        cd_com.resize(1014, 588)
        self.groupBox = QtGui.QGroupBox(cd_com)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 991, 41))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.cbxDevErr = QtGui.QCheckBox(self.groupBox)
        self.cbxDevErr.setGeometry(QtCore.QRect(40, 20, 125, 16))
        self.cbxDevErr.setObjectName(_fromUtf8("cbxDevErr"))
        self.groupBox_2 = QtGui.QGroupBox(cd_com)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 40, 991, 541))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.trComCfg = QtGui.QTreeWidget(self.groupBox_2)
        self.trComCfg.setGeometry(QtCore.QRect(10, 30, 341, 501))
        self.trComCfg.setObjectName(_fromUtf8("trComCfg"))
        item_0 = QtGui.QTreeWidgetItem(self.trComCfg)
        item_0 = QtGui.QTreeWidgetItem(self.trComCfg)
        self.tabCfg = QtGui.QTabWidget(self.groupBox_2)
        self.tabCfg.setGeometry(QtCore.QRect(510, 20, 471, 521))
        self.tabCfg.setObjectName(_fromUtf8("tabCfg"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 40, 381, 22))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lePduGrpName = QtGui.QLineEdit(self.layoutWidget)
        self.lePduGrpName.setObjectName(_fromUtf8("lePduGrpName"))
        self.horizontalLayout.addWidget(self.lePduGrpName)
        self.tabCfg.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 170, 431, 51))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 20, 391, 22))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.layoutWidget_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.cmbxPduSignalProcessing = QtGui.QComboBox(self.layoutWidget_4)
        self.cmbxPduSignalProcessing.setObjectName(_fromUtf8("cmbxPduSignalProcessing"))
        self.cmbxPduSignalProcessing.addItem(_fromUtf8(""))
        self.cmbxPduSignalProcessing.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.cmbxPduSignalProcessing)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 230, 431, 221))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 21, 391, 192))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.spbxMinDelayFactor = QtGui.QSpinBox(self.layoutWidget1)
        self.spbxMinDelayFactor.setObjectName(_fromUtf8("spbxMinDelayFactor"))
        self.horizontalLayout_7.addWidget(self.spbxMinDelayFactor)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        self.spbxDefaultValueForUnusedAreas = QtGui.QSpinBox(self.layoutWidget1)
        self.spbxDefaultValueForUnusedAreas.setObjectName(_fromUtf8("spbxDefaultValueForUnusedAreas"))
        self.horizontalLayout_8.addWidget(self.spbxDefaultValueForUnusedAreas)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_9.addWidget(self.label_9)
        self.cmbxPduTxMode = QtGui.QComboBox(self.layoutWidget1)
        self.cmbxPduTxMode.setObjectName(_fromUtf8("cmbxPduTxMode"))
        self.cmbxPduTxMode.addItem(_fromUtf8(""))
        self.cmbxPduTxMode.addItem(_fromUtf8(""))
        self.cmbxPduTxMode.addItem(_fromUtf8(""))
        self.cmbxPduTxMode.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.cmbxPduTxMode)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.spbxNumberOfRepetitions = QtGui.QSpinBox(self.layoutWidget1)
        self.spbxNumberOfRepetitions.setObjectName(_fromUtf8("spbxNumberOfRepetitions"))
        self.horizontalLayout_10.addWidget(self.spbxNumberOfRepetitions)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.label_38 = QtGui.QLabel(self.layoutWidget1)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_42.addWidget(self.label_38)
        self.spbxRepetitionPeriodFactor = QtGui.QSpinBox(self.layoutWidget1)
        self.spbxRepetitionPeriodFactor.setToolTip(_fromUtf8(""))
        self.spbxRepetitionPeriodFactor.setObjectName(_fromUtf8("spbxRepetitionPeriodFactor"))
        self.horizontalLayout_42.addWidget(self.spbxRepetitionPeriodFactor)
        self.verticalLayout.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_11.addWidget(self.label_11)
        self.spbxTimeOffsetFactor = QtGui.QSpinBox(self.layoutWidget1)
        self.spbxTimeOffsetFactor.setObjectName(_fromUtf8("spbxTimeOffsetFactor"))
        self.horizontalLayout_11.addWidget(self.spbxTimeOffsetFactor)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_12.addWidget(self.label_12)
        self.spbxTimePeriodFactor = QtGui.QSpinBox(self.layoutWidget1)
        self.spbxTimePeriodFactor.setObjectName(_fromUtf8("spbxTimePeriodFactor"))
        self.horizontalLayout_12.addWidget(self.spbxTimePeriodFactor)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.layoutWidget2 = QtGui.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(40, 22, 391, 136))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.leIPduName = QtGui.QLineEdit(self.layoutWidget2)
        self.leIPduName.setObjectName(_fromUtf8("leIPduName"))
        self.horizontalLayout_2.addWidget(self.leIPduName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cmbxGblPdu = QtGui.QComboBox(self.layoutWidget2)
        self.cmbxGblPdu.setMinimumSize(QtCore.QSize(300, 0))
        self.cmbxGblPdu.setObjectName(_fromUtf8("cmbxGblPdu"))
        self.horizontalLayout_3.addWidget(self.cmbxGblPdu)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.cmbxPduDirection = QtGui.QComboBox(self.layoutWidget2)
        self.cmbxPduDirection.setMinimumSize(QtCore.QSize(300, 0))
        self.cmbxPduDirection.setObjectName(_fromUtf8("cmbxPduDirection"))
        self.cmbxPduDirection.addItem(_fromUtf8(""))
        self.cmbxPduDirection.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cmbxPduDirection)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_13 = QtGui.QLabel(self.layoutWidget2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_13.addWidget(self.label_13)
        self.cmbxPduGrp = QtGui.QComboBox(self.layoutWidget2)
        self.cmbxPduGrp.setMinimumSize(QtCore.QSize(300, 0))
        self.cmbxPduGrp.setObjectName(_fromUtf8("cmbxPduGrp"))
        self.horizontalLayout_13.addWidget(self.cmbxPduGrp)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lePduCallout = QtGui.QLineEdit(self.layoutWidget2)
        self.lePduCallout.setObjectName(_fromUtf8("lePduCallout"))
        self.horizontalLayout_5.addWidget(self.lePduCallout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label_43 = QtGui.QLabel(self.tab_2)
        self.label_43.setGeometry(QtCore.QRect(30, 470, 291, 16))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.tabCfg.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 160, 431, 171))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 411, 136))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_18 = QtGui.QLabel(self.layoutWidget3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_19.addWidget(self.label_18)
        self.spbxSignalPosition = QtGui.QSpinBox(self.layoutWidget3)
        self.spbxSignalPosition.setObjectName(_fromUtf8("spbxSignalPosition"))
        self.horizontalLayout_19.addWidget(self.spbxSignalPosition)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_19 = QtGui.QLabel(self.layoutWidget3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_20.addWidget(self.label_19)
        self.spbxSignalLSBPosition = QtGui.QSpinBox(self.layoutWidget3)
        self.spbxSignalLSBPosition.setObjectName(_fromUtf8("spbxSignalLSBPosition"))
        self.horizontalLayout_20.addWidget(self.spbxSignalLSBPosition)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_20 = QtGui.QLabel(self.layoutWidget3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_21.addWidget(self.label_20)
        self.spbxSignalSize = QtGui.QSpinBox(self.layoutWidget3)
        self.spbxSignalSize.setObjectName(_fromUtf8("spbxSignalSize"))
        self.horizontalLayout_21.addWidget(self.spbxSignalSize)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_21 = QtGui.QLabel(self.layoutWidget3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_22.addWidget(self.label_21)
        self.leSignalInitValue = QtGui.QLineEdit(self.layoutWidget3)
        self.leSignalInitValue.setObjectName(_fromUtf8("leSignalInitValue"))
        self.horizontalLayout_22.addWidget(self.leSignalInitValue)
        self.verticalLayout_4.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.cbxSignalUpdateBitPosition = QtGui.QCheckBox(self.layoutWidget3)
        self.cbxSignalUpdateBitPosition.setObjectName(_fromUtf8("cbxSignalUpdateBitPosition"))
        self.horizontalLayout_23.addWidget(self.cbxSignalUpdateBitPosition)
        self.spbxSignalUpdateBitPosition = QtGui.QSpinBox(self.layoutWidget3)
        self.spbxSignalUpdateBitPosition.setObjectName(_fromUtf8("spbxSignalUpdateBitPosition"))
        self.horizontalLayout_23.addWidget(self.spbxSignalUpdateBitPosition)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 330, 431, 161))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.layoutWidget_9 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget_9.setGeometry(QtCore.QRect(10, 20, 411, 136))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_22 = QtGui.QLabel(self.layoutWidget_9)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_24.addWidget(self.label_22)
        self.spbxSignalTimeoutFactor = QtGui.QSpinBox(self.layoutWidget_9)
        self.spbxSignalTimeoutFactor.setObjectName(_fromUtf8("spbxSignalTimeoutFactor"))
        self.horizontalLayout_24.addWidget(self.spbxSignalTimeoutFactor)
        self.verticalLayout_6.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_23 = QtGui.QLabel(self.layoutWidget_9)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_25.addWidget(self.label_23)
        self.spbxSignalFirstTimeout = QtGui.QSpinBox(self.layoutWidget_9)
        self.spbxSignalFirstTimeout.setObjectName(_fromUtf8("spbxSignalFirstTimeout"))
        self.horizontalLayout_25.addWidget(self.spbxSignalFirstTimeout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_24 = QtGui.QLabel(self.layoutWidget_9)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_26.addWidget(self.label_24)
        self.cmbxSignalTimeoutAction = QtGui.QComboBox(self.layoutWidget_9)
        self.cmbxSignalTimeoutAction.setObjectName(_fromUtf8("cmbxSignalTimeoutAction"))
        self.cmbxSignalTimeoutAction.addItem(_fromUtf8(""))
        self.cmbxSignalTimeoutAction.addItem(_fromUtf8(""))
        self.horizontalLayout_26.addWidget(self.cmbxSignalTimeoutAction)
        self.verticalLayout_6.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_25 = QtGui.QLabel(self.layoutWidget_9)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_27.addWidget(self.label_25)
        self.leSignalNotification = QtGui.QLineEdit(self.layoutWidget_9)
        self.leSignalNotification.setObjectName(_fromUtf8("leSignalNotification"))
        self.horizontalLayout_27.addWidget(self.leSignalNotification)
        self.verticalLayout_6.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_26 = QtGui.QLabel(self.layoutWidget_9)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_28.addWidget(self.label_26)
        self.leSignalNotificationOnTimeout = QtGui.QLineEdit(self.layoutWidget_9)
        self.leSignalNotificationOnTimeout.setObjectName(_fromUtf8("leSignalNotificationOnTimeout"))
        self.horizontalLayout_28.addWidget(self.leSignalNotificationOnTimeout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_28)
        self.layoutWidget4 = QtGui.QWidget(self.tab_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(21, 11, 433, 146))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_14 = QtGui.QLabel(self.layoutWidget4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_14.addWidget(self.label_14)
        self.leSignalName = QtGui.QLineEdit(self.layoutWidget4)
        self.leSignalName.setObjectName(_fromUtf8("leSignalName"))
        self.horizontalLayout_14.addWidget(self.leSignalName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_15 = QtGui.QLabel(self.layoutWidget4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_15.addWidget(self.label_15)
        self.cmbxSignalType = QtGui.QComboBox(self.layoutWidget4)
        self.cmbxSignalType.setMinimumSize(QtCore.QSize(300, 0))
        self.cmbxSignalType.setObjectName(_fromUtf8("cmbxSignalType"))
        self.cmbxSignalType.addItem(_fromUtf8(""))
        self.cmbxSignalType.addItem(_fromUtf8(""))
        self.cmbxSignalType.addItem(_fromUtf8(""))
        self.cmbxSignalType.addItem(_fromUtf8(""))
        self.cmbxSignalType.addItem(_fromUtf8(""))
        self.cmbxSignalType.addItem(_fromUtf8(""))
        self.cmbxSignalType.addItem(_fromUtf8(""))
        self.cmbxSignalType.addItem(_fromUtf8(""))
        self.cmbxSignalType.addItem(_fromUtf8(""))
        self.horizontalLayout_15.addWidget(self.cmbxSignalType)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_16 = QtGui.QLabel(self.layoutWidget4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_16.addWidget(self.label_16)
        self.cmbxSignalEndianess = QtGui.QComboBox(self.layoutWidget4)
        self.cmbxSignalEndianess.setMinimumSize(QtCore.QSize(300, 0))
        self.cmbxSignalEndianess.setObjectName(_fromUtf8("cmbxSignalEndianess"))
        self.cmbxSignalEndianess.addItem(_fromUtf8(""))
        self.cmbxSignalEndianess.addItem(_fromUtf8(""))
        self.cmbxSignalEndianess.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.cmbxSignalEndianess)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_17 = QtGui.QLabel(self.layoutWidget4)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_17.addWidget(self.label_17)
        self.cmbxSignalTxProperty = QtGui.QComboBox(self.layoutWidget4)
        self.cmbxSignalTxProperty.setMinimumSize(QtCore.QSize(300, 0))
        self.cmbxSignalTxProperty.setObjectName(_fromUtf8("cmbxSignalTxProperty"))
        self.cmbxSignalTxProperty.addItem(_fromUtf8(""))
        self.cmbxSignalTxProperty.addItem(_fromUtf8(""))
        self.horizontalLayout_17.addWidget(self.cmbxSignalTxProperty)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.cbxAutoSysSignalMap = QtGui.QCheckBox(self.layoutWidget4)
        self.cbxAutoSysSignalMap.setObjectName(_fromUtf8("cbxAutoSysSignalMap"))
        self.horizontalLayout_18.addWidget(self.cbxAutoSysSignalMap)
        self.cmbxAutoSysSignalMap = QtGui.QComboBox(self.layoutWidget4)
        self.cmbxAutoSysSignalMap.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbxAutoSysSignalMap.setObjectName(_fromUtf8("cmbxAutoSysSignalMap"))
        self.horizontalLayout_18.addWidget(self.cmbxAutoSysSignalMap)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.tabCfg.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 170, 431, 111))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.layoutWidget5 = QtGui.QWidget(self.groupBox_7)
        self.layoutWidget5.setGeometry(QtCore.QRect(11, 21, 411, 80))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_28 = QtGui.QLabel(self.layoutWidget5)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_30.addWidget(self.label_28)
        self.spbxSignalGrpPosition = QtGui.QSpinBox(self.layoutWidget5)
        self.spbxSignalGrpPosition.setObjectName(_fromUtf8("spbxSignalGrpPosition"))
        self.horizontalLayout_30.addWidget(self.spbxSignalGrpPosition)
        self.verticalLayout_8.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_31 = QtGui.QLabel(self.layoutWidget5)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_34.addWidget(self.label_31)
        self.spbxSignalGrpSize = QtGui.QSpinBox(self.layoutWidget5)
        self.spbxSignalGrpSize.setObjectName(_fromUtf8("spbxSignalGrpSize"))
        self.horizontalLayout_34.addWidget(self.spbxSignalGrpSize)
        self.verticalLayout_8.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.cbxSignalGrpUpdateBitPosition = QtGui.QCheckBox(self.layoutWidget5)
        self.cbxSignalGrpUpdateBitPosition.setObjectName(_fromUtf8("cbxSignalGrpUpdateBitPosition"))
        self.horizontalLayout_36.addWidget(self.cbxSignalGrpUpdateBitPosition)
        self.spbxSignalGrpUpdateBitPosition = QtGui.QSpinBox(self.layoutWidget5)
        self.spbxSignalGrpUpdateBitPosition.setObjectName(_fromUtf8("spbxSignalGrpUpdateBitPosition"))
        self.horizontalLayout_36.addWidget(self.spbxSignalGrpUpdateBitPosition)
        self.verticalLayout_8.addLayout(self.horizontalLayout_36)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 340, 431, 141))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.layoutWidget6 = QtGui.QWidget(self.groupBox_8)
        self.layoutWidget6.setGeometry(QtCore.QRect(11, 21, 411, 108))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_29 = QtGui.QLabel(self.layoutWidget6)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_31.addWidget(self.label_29)
        self.spbxSignalGrpTimeoutFactor = QtGui.QSpinBox(self.layoutWidget6)
        self.spbxSignalGrpTimeoutFactor.setObjectName(_fromUtf8("spbxSignalGrpTimeoutFactor"))
        self.horizontalLayout_31.addWidget(self.spbxSignalGrpTimeoutFactor)
        self.verticalLayout_9.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_32 = QtGui.QLabel(self.layoutWidget6)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_35.addWidget(self.label_32)
        self.spbxSignalGrpFirstTimeout = QtGui.QSpinBox(self.layoutWidget6)
        self.spbxSignalGrpFirstTimeout.setObjectName(_fromUtf8("spbxSignalGrpFirstTimeout"))
        self.horizontalLayout_35.addWidget(self.spbxSignalGrpFirstTimeout)
        self.verticalLayout_9.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.label_34 = QtGui.QLabel(self.layoutWidget6)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_38.addWidget(self.label_34)
        self.leSignalGrpNotification = QtGui.QLineEdit(self.layoutWidget6)
        self.leSignalGrpNotification.setObjectName(_fromUtf8("leSignalGrpNotification"))
        self.horizontalLayout_38.addWidget(self.leSignalGrpNotification)
        self.verticalLayout_9.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.label_35 = QtGui.QLabel(self.layoutWidget6)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_39.addWidget(self.label_35)
        self.leSignalGrpNotificationOnTimeout = QtGui.QLineEdit(self.layoutWidget6)
        self.leSignalGrpNotificationOnTimeout.setObjectName(_fromUtf8("leSignalGrpNotificationOnTimeout"))
        self.horizontalLayout_39.addWidget(self.leSignalGrpNotificationOnTimeout)
        self.verticalLayout_9.addLayout(self.horizontalLayout_39)
        self.layoutWidget7 = QtGui.QWidget(self.tab_4)
        self.layoutWidget7.setGeometry(QtCore.QRect(21, 11, 433, 90))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_27 = QtGui.QLabel(self.layoutWidget7)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_29.addWidget(self.label_27)
        self.leSignalGrpName = QtGui.QLineEdit(self.layoutWidget7)
        self.leSignalGrpName.setObjectName(_fromUtf8("leSignalGrpName"))
        self.horizontalLayout_29.addWidget(self.leSignalGrpName)
        self.verticalLayout_7.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_30 = QtGui.QLabel(self.layoutWidget7)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_32.addWidget(self.label_30)
        self.cmbxSignalGrpTxProperty = QtGui.QComboBox(self.layoutWidget7)
        self.cmbxSignalGrpTxProperty.setMinimumSize(QtCore.QSize(300, 0))
        self.cmbxSignalGrpTxProperty.setObjectName(_fromUtf8("cmbxSignalGrpTxProperty"))
        self.cmbxSignalGrpTxProperty.addItem(_fromUtf8(""))
        self.cmbxSignalGrpTxProperty.addItem(_fromUtf8(""))
        self.horizontalLayout_32.addWidget(self.cmbxSignalGrpTxProperty)
        self.verticalLayout_7.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.cbxAutoSysSignalGrpMap = QtGui.QCheckBox(self.layoutWidget7)
        self.cbxAutoSysSignalGrpMap.setObjectName(_fromUtf8("cbxAutoSysSignalGrpMap"))
        self.horizontalLayout_33.addWidget(self.cbxAutoSysSignalGrpMap)
        self.cmbxAutoSysSignalGrpMap = QtGui.QComboBox(self.layoutWidget7)
        self.cmbxAutoSysSignalGrpMap.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbxAutoSysSignalGrpMap.setObjectName(_fromUtf8("cmbxAutoSysSignalGrpMap"))
        self.horizontalLayout_33.addWidget(self.cmbxAutoSysSignalGrpMap)
        self.verticalLayout_7.addLayout(self.horizontalLayout_33)
        self.tabCfg.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 160, 431, 141))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.layoutWidget8 = QtGui.QWidget(self.groupBox_9)
        self.layoutWidget8.setGeometry(QtCore.QRect(11, 21, 411, 108))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_44 = QtGui.QHBoxLayout()
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        self.label_39 = QtGui.QLabel(self.layoutWidget8)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_44.addWidget(self.label_39)
        self.spbxGrpSignalPosition = QtGui.QSpinBox(self.layoutWidget8)
        self.spbxGrpSignalPosition.setObjectName(_fromUtf8("spbxGrpSignalPosition"))
        self.horizontalLayout_44.addWidget(self.spbxGrpSignalPosition)
        self.verticalLayout_11.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setObjectName(_fromUtf8("horizontalLayout_45"))
        self.label_40 = QtGui.QLabel(self.layoutWidget8)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_45.addWidget(self.label_40)
        self.spbxGrpSignalLSBPosition = QtGui.QSpinBox(self.layoutWidget8)
        self.spbxGrpSignalLSBPosition.setObjectName(_fromUtf8("spbxGrpSignalLSBPosition"))
        self.horizontalLayout_45.addWidget(self.spbxGrpSignalLSBPosition)
        self.verticalLayout_11.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtGui.QHBoxLayout()
        self.horizontalLayout_46.setObjectName(_fromUtf8("horizontalLayout_46"))
        self.label_41 = QtGui.QLabel(self.layoutWidget8)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_46.addWidget(self.label_41)
        self.spbxGrpSignalSize = QtGui.QSpinBox(self.layoutWidget8)
        self.spbxGrpSignalSize.setObjectName(_fromUtf8("spbxGrpSignalSize"))
        self.horizontalLayout_46.addWidget(self.spbxGrpSignalSize)
        self.verticalLayout_11.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtGui.QHBoxLayout()
        self.horizontalLayout_47.setObjectName(_fromUtf8("horizontalLayout_47"))
        self.label_42 = QtGui.QLabel(self.layoutWidget8)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.horizontalLayout_47.addWidget(self.label_42)
        self.leGrpSignalInitValue = QtGui.QLineEdit(self.layoutWidget8)
        self.leGrpSignalInitValue.setObjectName(_fromUtf8("leGrpSignalInitValue"))
        self.horizontalLayout_47.addWidget(self.leGrpSignalInitValue)
        self.verticalLayout_11.addLayout(self.horizontalLayout_47)
        self.layoutWidget9 = QtGui.QWidget(self.tab_5)
        self.layoutWidget9.setGeometry(QtCore.QRect(12, 12, 433, 118))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_33 = QtGui.QLabel(self.layoutWidget9)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_37.addWidget(self.label_33)
        self.leGrpSignalName = QtGui.QLineEdit(self.layoutWidget9)
        self.leGrpSignalName.setObjectName(_fromUtf8("leGrpSignalName"))
        self.horizontalLayout_37.addWidget(self.leGrpSignalName)
        self.verticalLayout_10.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.label_36 = QtGui.QLabel(self.layoutWidget9)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_40.addWidget(self.label_36)
        self.cmbxGrpSignalType = QtGui.QComboBox(self.layoutWidget9)
        self.cmbxGrpSignalType.setMinimumSize(QtCore.QSize(300, 0))
        self.cmbxGrpSignalType.setObjectName(_fromUtf8("cmbxGrpSignalType"))
        self.cmbxGrpSignalType.addItem(_fromUtf8(""))
        self.cmbxGrpSignalType.addItem(_fromUtf8(""))
        self.cmbxGrpSignalType.addItem(_fromUtf8(""))
        self.cmbxGrpSignalType.addItem(_fromUtf8(""))
        self.cmbxGrpSignalType.addItem(_fromUtf8(""))
        self.cmbxGrpSignalType.addItem(_fromUtf8(""))
        self.cmbxGrpSignalType.addItem(_fromUtf8(""))
        self.cmbxGrpSignalType.addItem(_fromUtf8(""))
        self.horizontalLayout_40.addWidget(self.cmbxGrpSignalType)
        self.verticalLayout_10.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.label_37 = QtGui.QLabel(self.layoutWidget9)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_41.addWidget(self.label_37)
        self.cmbxGrpSignalEndianess = QtGui.QComboBox(self.layoutWidget9)
        self.cmbxGrpSignalEndianess.setMinimumSize(QtCore.QSize(300, 0))
        self.cmbxGrpSignalEndianess.setObjectName(_fromUtf8("cmbxGrpSignalEndianess"))
        self.cmbxGrpSignalEndianess.addItem(_fromUtf8(""))
        self.cmbxGrpSignalEndianess.addItem(_fromUtf8(""))
        self.cmbxGrpSignalEndianess.addItem(_fromUtf8(""))
        self.horizontalLayout_41.addWidget(self.cmbxGrpSignalEndianess)
        self.verticalLayout_10.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.cbxAutoSysGrpSignalMap = QtGui.QCheckBox(self.layoutWidget9)
        self.cbxAutoSysGrpSignalMap.setObjectName(_fromUtf8("cbxAutoSysGrpSignalMap"))
        self.horizontalLayout_43.addWidget(self.cbxAutoSysGrpSignalMap)
        self.cmbxAutoSysGrpSignalMap = QtGui.QComboBox(self.layoutWidget9)
        self.cmbxAutoSysGrpSignalMap.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbxAutoSysGrpSignalMap.setObjectName(_fromUtf8("cmbxAutoSysGrpSignalMap"))
        self.horizontalLayout_43.addWidget(self.cmbxAutoSysGrpSignalMap)
        self.verticalLayout_10.addLayout(self.horizontalLayout_43)
        self.tabCfg.addTab(self.tab_5, _fromUtf8(""))
        self.layoutWidget10 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget10.setGeometry(QtCore.QRect(370, 60, 121, 83))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.btnAdd = QtGui.QPushButton(self.layoutWidget10)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.verticalLayout_5.addWidget(self.btnAdd)
        self.btnAdd2 = QtGui.QPushButton(self.layoutWidget10)
        self.btnAdd2.setObjectName(_fromUtf8("btnAdd2"))
        self.verticalLayout_5.addWidget(self.btnAdd2)
        self.btnDel = QtGui.QPushButton(self.layoutWidget10)
        self.btnDel.setObjectName(_fromUtf8("btnDel"))
        self.verticalLayout_5.addWidget(self.btnDel)

        self.retranslateUi(cd_com)
        self.tabCfg.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(cd_com)

    def retranslateUi(self, cd_com):
        cd_com.setWindowTitle(QtGui.QApplication.translate("cd_com", "Com<Communicatio Stack>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("cd_com", "Com General", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxDevErr.setText(QtGui.QApplication.translate("cd_com", "DevErrorDetection", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("cd_com", "Com Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.trComCfg.headerItem().setText(0, QtGui.QApplication.translate("cd_com", "Com", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.trComCfg.isSortingEnabled()
        self.trComCfg.setSortingEnabled(False)
        self.trComCfg.topLevelItem(0).setText(0, QtGui.QApplication.translate("cd_com", "Pdu Group", None, QtGui.QApplication.UnicodeUTF8))
        self.trComCfg.topLevelItem(1).setText(0, QtGui.QApplication.translate("cd_com", "Pdus", None, QtGui.QApplication.UnicodeUTF8))
        self.trComCfg.setSortingEnabled(__sortingEnabled)
        self.label.setText(QtGui.QApplication.translate("cd_com", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCfg.setTabText(self.tabCfg.indexOf(self.tab), QtGui.QApplication.translate("cd_com", "Pdu Group", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("cd_com", "Rx options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("cd_com", "Rx Signal Processing:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxPduSignalProcessing.setItemText(0, QtGui.QApplication.translate("cd_com", "IMMEDIATE", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxPduSignalProcessing.setItemText(1, QtGui.QApplication.translate("cd_com", "DEFERRED", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("cd_com", "Tx options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("cd_com", "Minimum delay factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxMinDelayFactor.setToolTip(QtGui.QApplication.translate("cd_com", "uint in MainFunction Period", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("cd_com", "Default value for unused areas:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("cd_com", "Tx Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxPduTxMode.setItemText(0, QtGui.QApplication.translate("cd_com", "DIRECT", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxPduTxMode.setItemText(1, QtGui.QApplication.translate("cd_com", "MIXED", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxPduTxMode.setItemText(2, QtGui.QApplication.translate("cd_com", "NONE", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxPduTxMode.setItemText(3, QtGui.QApplication.translate("cd_com", "PERIODIC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("cd_com", "Number of repetitions:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("cd_com", "Repetition period factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("cd_com", "Time offset factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxTimeOffsetFactor.setToolTip(QtGui.QApplication.translate("cd_com", "uint in MainFunction Period", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("cd_com", "Time period factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxTimePeriodFactor.setToolTip(QtGui.QApplication.translate("cd_com", "uint in MainFunction Period", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("cd_com", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("cd_com", "Global Pdu:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("cd_com", "Direction:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxPduDirection.setToolTip(QtGui.QApplication.translate("cd_com", "Shoud be consistent with the Global Pdu,if TX,SEND; if RX,RECEIVE.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxPduDirection.setItemText(0, QtGui.QApplication.translate("cd_com", "SEND", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxPduDirection.setItemText(1, QtGui.QApplication.translate("cd_com", "RECEIVE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("cd_com", "Pdu Group:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("cd_com", "Callout:", None, QtGui.QApplication.UnicodeUTF8))
        self.lePduCallout.setToolTip(QtGui.QApplication.translate("cd_com", "If unused,input NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("cd_com", "Note:IPDU size cann\'t be bigger than 8 bytes.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCfg.setTabText(self.tabCfg.indexOf(self.tab_2), QtGui.QApplication.translate("cd_com", "General I-PDU", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("cd_com", "Data Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("cd_com", "Position(bit):", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxSignalPosition.setToolTip(QtGui.QApplication.translate("cd_com", "Must be the times of eight.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("cd_com", "Position(Signal LSB):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("cd_com", "Size(bits):", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxSignalSize.setToolTip(QtGui.QApplication.translate("cd_com", "Range 0 to 63.\n"
"Range 0 to 4095 for uint8_n signal types", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("cd_com", "Initial value:", None, QtGui.QApplication.UnicodeUTF8))
        self.leSignalInitValue.setToolTip(QtGui.QApplication.translate("cd_com", "if type is UINT8_N or UNIT8_DYN,please in put init value with spac \' \' to spearete each other.", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSignalUpdateBitPosition.setText(QtGui.QApplication.translate("cd_com", "Update bit position:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("cd_com", "Timeouts and Notifications", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("cd_com", "Timeout Factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxSignalTimeoutFactor.setToolTip(QtGui.QApplication.translate("cd_com", "uint in MainFunction Period", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("cd_com", "First timeout:", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxSignalFirstTimeout.setToolTip(QtGui.QApplication.translate("cd_com", "uint in MainFunction Period", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("cd_com", "Timeout action:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalTimeoutAction.setToolTip(QtGui.QApplication.translate("cd_com", "For Tx signal,configure this has no meaning.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalTimeoutAction.setItemText(0, QtGui.QApplication.translate("cd_com", "REPLACE", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalTimeoutAction.setItemText(1, QtGui.QApplication.translate("cd_com", "NONE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("cd_com", "Notification(function):", None, QtGui.QApplication.UnicodeUTF8))
        self.leSignalNotification.setToolTip(QtGui.QApplication.translate("cd_com", "input \"NULL\" to turn it off, if you want", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("cd_com", "Notification on timeout(function):", None, QtGui.QApplication.UnicodeUTF8))
        self.leSignalNotificationOnTimeout.setToolTip(QtGui.QApplication.translate("cd_com", "input \"NULL\" to turn it off, if you want", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("cd_com", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("cd_com", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalType.setToolTip(QtGui.QApplication.translate("cd_com", "for UINT8_DYN type, the signal must be the last item and no signal group is allowed for the signal owner IPDU.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalType.setItemText(0, QtGui.QApplication.translate("cd_com", "BOOLEAN", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalType.setItemText(1, QtGui.QApplication.translate("cd_com", "UINT8", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalType.setItemText(2, QtGui.QApplication.translate("cd_com", "UINT16", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalType.setItemText(3, QtGui.QApplication.translate("cd_com", "UINT32", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalType.setItemText(4, QtGui.QApplication.translate("cd_com", "UINT8_N", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalType.setItemText(5, QtGui.QApplication.translate("cd_com", "UINT8_DYN", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalType.setItemText(6, QtGui.QApplication.translate("cd_com", "SINT8", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalType.setItemText(7, QtGui.QApplication.translate("cd_com", "SINT16", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalType.setItemText(8, QtGui.QApplication.translate("cd_com", "SINT32", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("cd_com", "Endianess:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalEndianess.setToolTip(QtGui.QApplication.translate("cd_com", "if type is UINT8_DYN,then only COM_OPAQUE is allowed.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalEndianess.setItemText(0, QtGui.QApplication.translate("cd_com", "COM_BIG_ENDIAN", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalEndianess.setItemText(1, QtGui.QApplication.translate("cd_com", "COM_LITTLE_ENDIAN", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalEndianess.setItemText(2, QtGui.QApplication.translate("cd_com", "COM_OPAQUE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("cd_com", "Transfer Property:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalTxProperty.setToolTip(QtGui.QApplication.translate("cd_com", "When this signal is asigned to a RX IPdu,configure transfer property has no meaning.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalTxProperty.setItemText(0, QtGui.QApplication.translate("cd_com", "PENDING", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalTxProperty.setItemText(1, QtGui.QApplication.translate("cd_com", "TRIGGERED", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxAutoSysSignalMap.setText(QtGui.QApplication.translate("cd_com", "Override automatic system \n"
"signal mapping:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCfg.setTabText(self.tabCfg.indexOf(self.tab_3), QtGui.QApplication.translate("cd_com", "General Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("cd_com", "Data Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("cd_com", "Position(bit):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("cd_com", "Size(bits):", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSignalGrpUpdateBitPosition.setText(QtGui.QApplication.translate("cd_com", "Update bit position:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("cd_com", "Timeouts and Notifications", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("cd_com", "Timeout Factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxSignalGrpTimeoutFactor.setToolTip(QtGui.QApplication.translate("cd_com", "uint in MainFunction Period", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("cd_com", "First timeout:", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxSignalGrpFirstTimeout.setToolTip(QtGui.QApplication.translate("cd_com", "uint in MainFunction Period", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("cd_com", "Notification(function):", None, QtGui.QApplication.UnicodeUTF8))
        self.leSignalGrpNotification.setToolTip(QtGui.QApplication.translate("cd_com", "input \"NULL\" to turn it off, if you want", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("cd_com", "Notification on timeout(function):", None, QtGui.QApplication.UnicodeUTF8))
        self.leSignalGrpNotificationOnTimeout.setToolTip(QtGui.QApplication.translate("cd_com", "input \"NULL\" to turn it off, if you want", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("cd_com", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("cd_com", "Transfer Property:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalGrpTxProperty.setItemText(0, QtGui.QApplication.translate("cd_com", "PENDING", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSignalGrpTxProperty.setItemText(1, QtGui.QApplication.translate("cd_com", "TRIGGERED", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxAutoSysSignalGrpMap.setText(QtGui.QApplication.translate("cd_com", "Override automatic system \n"
"signal mapping:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCfg.setTabText(self.tabCfg.indexOf(self.tab_4), QtGui.QApplication.translate("cd_com", "Signal Group", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("cd_com", "Data Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("cd_com", "Position(bit):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("cd_com", "Position(Signal LSB):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("cd_com", "Size(bits):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("cd_com", "Initial value:", None, QtGui.QApplication.UnicodeUTF8))
        self.leGrpSignalInitValue.setToolTip(QtGui.QApplication.translate("cd_com", "if type is UINT8_N,please in put init value with spac \' \' to spearete each other.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("cd_com", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("cd_com", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxGrpSignalType.setItemText(0, QtGui.QApplication.translate("cd_com", "BOOLEAN", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxGrpSignalType.setItemText(1, QtGui.QApplication.translate("cd_com", "UINT8", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxGrpSignalType.setItemText(2, QtGui.QApplication.translate("cd_com", "UINT16", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxGrpSignalType.setItemText(3, QtGui.QApplication.translate("cd_com", "UINT32", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxGrpSignalType.setItemText(4, QtGui.QApplication.translate("cd_com", "UINT8_N", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxGrpSignalType.setItemText(5, QtGui.QApplication.translate("cd_com", "SINT8", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxGrpSignalType.setItemText(6, QtGui.QApplication.translate("cd_com", "SINT16", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxGrpSignalType.setItemText(7, QtGui.QApplication.translate("cd_com", "SINT32", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("cd_com", "Endianess:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxGrpSignalEndianess.setItemText(0, QtGui.QApplication.translate("cd_com", "COM_BIG_ENDIAN", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxGrpSignalEndianess.setItemText(1, QtGui.QApplication.translate("cd_com", "COM_LITTLE_ENDIAN", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxGrpSignalEndianess.setItemText(2, QtGui.QApplication.translate("cd_com", "COM_OPAQUE", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxAutoSysGrpSignalMap.setText(QtGui.QApplication.translate("cd_com", "Override automatic system \n"
"signal mapping:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCfg.setTabText(self.tabCfg.indexOf(self.tab_5), QtGui.QApplication.translate("cd_com", "Group Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("cd_com", "Add Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd2.setText(QtGui.QApplication.translate("cd_com", "Add Signal Group", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDel.setText(QtGui.QApplication.translate("cd_com", "Delete", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    cd_com = QtGui.QDialog()
    ui = Ui_cd_com()
    ui.setupUi(cd_com)
    cd_com.show()
    sys.exit(app.exec_())

