# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\parai@foxmail.com\github\gainos-tk\tool\gainos-studio\ui\forms\cd_nm.ui'
#
# Created: Sun Jul 14 16:41:39 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_cd_nm(object):
    def setupUi(self, cd_nm):
        cd_nm.setObjectName(_fromUtf8("cd_nm"))
        cd_nm.resize(945, 512)
        cd_nm.setStyleSheet(_fromUtf8("font: 12pt \"Consolas\";"))
        self.groupBox = QtGui.QGroupBox(cd_nm)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 931, 101))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 691, 56))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.cbxDevErr = QtGui.QCheckBox(self.layoutWidget)
        self.cbxDevErr.setObjectName(_fromUtf8("cbxDevErr"))
        self.verticalLayout_6.addWidget(self.cbxDevErr)
        self.cbxNodeDetection = QtGui.QCheckBox(self.layoutWidget)
        self.cbxNodeDetection.setObjectName(_fromUtf8("cbxNodeDetection"))
        self.verticalLayout_6.addWidget(self.cbxNodeDetection)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.cbxVersionInfoApi = QtGui.QCheckBox(self.layoutWidget)
        self.cbxVersionInfoApi.setObjectName(_fromUtf8("cbxVersionInfoApi"))
        self.verticalLayout_7.addWidget(self.cbxVersionInfoApi)
        self.cbxNodeId = QtGui.QCheckBox(self.layoutWidget)
        self.cbxNodeId.setObjectName(_fromUtf8("cbxNodeId"))
        self.verticalLayout_7.addWidget(self.cbxNodeId)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.cbxUserData = QtGui.QCheckBox(self.layoutWidget)
        self.cbxUserData.setObjectName(_fromUtf8("cbxUserData"))
        self.verticalLayout_8.addWidget(self.cbxUserData)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.groupBox_2 = QtGui.QGroupBox(cd_nm)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 931, 401))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.tabCfg = QtGui.QTabWidget(self.groupBox_2)
        self.tabCfg.setGeometry(QtCore.QRect(420, 10, 511, 381))
        self.tabCfg.setObjectName(_fromUtf8("tabCfg"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 21, 481, 130))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_44 = QtGui.QLabel(self.layoutWidget1)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_15.addWidget(self.label_44)
        self.leChanneName = QtGui.QLineEdit(self.layoutWidget1)
        self.leChanneName.setText(_fromUtf8(""))
        self.leChanneName.setObjectName(_fromUtf8("leChanneName"))
        self.horizontalLayout_15.addWidget(self.leChanneName)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_32 = QtGui.QLabel(self.layoutWidget1)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_16.addWidget(self.label_32)
        self.cmbxBusType = QtGui.QComboBox(self.layoutWidget1)
        self.cmbxBusType.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbxBusType.setToolTip(_fromUtf8(""))
        self.cmbxBusType.setObjectName(_fromUtf8("cmbxBusType"))
        self.cmbxBusType.addItem(_fromUtf8(""))
        self.cmbxBusType.addItem(_fromUtf8(""))
        self.cmbxBusType.addItem(_fromUtf8(""))
        self.cmbxBusType.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.cmbxBusType)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_33 = QtGui.QLabel(self.layoutWidget1)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_17.addWidget(self.label_33)
        self.cmbxComMChannel = QtGui.QComboBox(self.layoutWidget1)
        self.cmbxComMChannel.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbxComMChannel.setToolTip(_fromUtf8(""))
        self.cmbxComMChannel.setObjectName(_fromUtf8("cmbxComMChannel"))
        self.horizontalLayout_17.addWidget(self.cmbxComMChannel)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_34 = QtGui.QLabel(self.layoutWidget1)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_18.addWidget(self.label_34)
        self.cmbxNmChannel = QtGui.QComboBox(self.layoutWidget1)
        self.cmbxNmChannel.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbxNmChannel.setObjectName(_fromUtf8("cmbxNmChannel"))
        self.horizontalLayout_18.addWidget(self.cmbxNmChannel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.tabCfg.addTab(self.tab_3, _fromUtf8(""))
        self.btn1 = QtGui.QPushButton(self.groupBox_2)
        self.btn1.setGeometry(QtCore.QRect(291, 55, 111, 23))
        self.btn1.setObjectName(_fromUtf8("btn1"))
        self.trNmCfg = QtGui.QTreeWidget(self.groupBox_2)
        self.trNmCfg.setGeometry(QtCore.QRect(10, 30, 256, 361))
        self.trNmCfg.setObjectName(_fromUtf8("trNmCfg"))
        item_0 = QtGui.QTreeWidgetItem(self.trNmCfg)

        self.retranslateUi(cd_nm)
        self.tabCfg.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(cd_nm)

    def retranslateUi(self, cd_nm):
        cd_nm.setWindowTitle(QtGui.QApplication.translate("cd_nm", "Network Management", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("cd_nm", "Nm General", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxDevErr.setText(QtGui.QApplication.translate("cd_nm", "DevErrorDetection", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxNodeDetection.setText(QtGui.QApplication.translate("cd_nm", "Node Detection Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxVersionInfoApi.setText(QtGui.QApplication.translate("cd_nm", "VersionInfoApi", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxNodeId.setText(QtGui.QApplication.translate("cd_nm", "Node Id Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxUserData.setText(QtGui.QApplication.translate("cd_nm", "User Data Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("cd_nm", "Nm Entities", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("cd_nm", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("cd_nm", "Bus Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxBusType.setItemText(0, QtGui.QApplication.translate("cd_nm", "NM_BUSNM_CANNM", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxBusType.setItemText(1, QtGui.QApplication.translate("cd_nm", "NM_BUSNM_FRNM", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxBusType.setItemText(2, QtGui.QApplication.translate("cd_nm", "NM_BUSNM_LINNM", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxBusType.setItemText(3, QtGui.QApplication.translate("cd_nm", "NM_BUSNM_UNDEF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("cd_nm", "ComM Channel:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("cd_nm", "Nm Channel:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxNmChannel.setToolTip(QtGui.QApplication.translate("cd_nm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">low layer such as CanNm,LinNm ...</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCfg.setTabText(self.tabCfg.indexOf(self.tab_3), QtGui.QApplication.translate("cd_nm", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.btn1.setText(QtGui.QApplication.translate("cd_nm", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.trNmCfg.headerItem().setText(0, QtGui.QApplication.translate("cd_nm", "Nm", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.trNmCfg.isSortingEnabled()
        self.trNmCfg.setSortingEnabled(False)
        self.trNmCfg.topLevelItem(0).setText(0, QtGui.QApplication.translate("cd_nm", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.trNmCfg.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    cd_nm = QtGui.QDialog()
    ui = Ui_cd_nm()
    ui.setupUi(cd_nm)
    cd_nm.show()
    sys.exit(app.exec_())

