# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\parai@foxmail.com\github\gainos-tk\tool\gainos-studio\ui\forms\cd_dcm.ui'
#
# Created: Thu May 23 23:49:01 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_cd_dcm(object):
    def setupUi(self, cd_dcm):
        cd_dcm.setObjectName(_fromUtf8("cd_dcm"))
        cd_dcm.resize(1068, 632)
        cd_dcm.setStyleSheet(_fromUtf8("font: 12pt \"Consolas\";"))
        self.groupBox = QtGui.QGroupBox(cd_dcm)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 371, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(11, 20, 266, 23))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(11, 110, 242, 27))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtGui.QSpinBox(self.widget)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout.addWidget(self.spinBox)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(11, 50, 194, 23))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(11, 80, 167, 23))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.tabWidget = QtGui.QTabWidget(cd_dcm)
        self.tabWidget.setGeometry(QtCore.QRect(390, 10, 671, 131))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.widget1 = QtGui.QWidget(self.tab)
        self.widget1.setGeometry(QtCore.QRect(20, 20, 351, 58))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.checkBox_4 = QtGui.QCheckBox(self.widget1)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.verticalLayout_5.addWidget(self.checkBox_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_2 = QtGui.QSpinBox(self.widget1)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.widget2 = QtGui.QWidget(self.tab_2)
        self.widget2.setGeometry(QtCore.QRect(11, 11, 641, 77))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.widget2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_3 = QtGui.QSpinBox(self.widget2)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.horizontalLayout_3.addWidget(self.spinBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.widget2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spinBox_4 = QtGui.QSpinBox(self.widget2)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.horizontalLayout_4.addWidget(self.spinBox_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.widget2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.spinBox_7 = QtGui.QSpinBox(self.widget2)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.horizontalLayout_6.addWidget(self.spinBox_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.widget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinBox_5 = QtGui.QSpinBox(self.widget2)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.horizontalLayout_5.addWidget(self.spinBox_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.layoutWidget_5 = QtGui.QWidget(self.tab_3)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 20, 329, 40))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_8 = QtGui.QLabel(self.layoutWidget_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_7.addWidget(self.label_8)
        self.spinBox_8 = QtGui.QSpinBox(self.layoutWidget_5)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.horizontalLayout_7.addWidget(self.spinBox_8)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(cd_dcm)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 1051, 481))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.treeWidget = QtGui.QTreeWidget(self.groupBox_2)
        self.treeWidget.setGeometry(QtCore.QRect(10, 30, 256, 441))
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        self.tabDcm = QtGui.QTabWidget(self.groupBox_2)
        self.tabDcm.setGeometry(QtCore.QRect(440, 20, 601, 451))
        self.tabDcm.setObjectName(_fromUtf8("tabDcm"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.widget3 = QtGui.QWidget(self.tab_4)
        self.widget3.setGeometry(QtCore.QRect(20, 20, 331, 62))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_6 = QtGui.QLabel(self.widget3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.lineEdit = QtGui.QLineEdit(self.widget3)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_9.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_9 = QtGui.QLabel(self.widget3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.spinBox_6 = QtGui.QSpinBox(self.widget3)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.horizontalLayout_10.addWidget(self.spinBox_6)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.tabDcm.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.widget4 = QtGui.QWidget(self.tab_5)
        self.widget4.setGeometry(QtCore.QRect(20, 21, 411, 120))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget4)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_11 = QtGui.QLabel(self.widget4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_12.addWidget(self.label_11)
        self.lineEdit_2 = QtGui.QLineEdit(self.widget4)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_12.addWidget(self.lineEdit_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.checkBox_6 = QtGui.QCheckBox(self.widget4)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.verticalLayout_6.addWidget(self.checkBox_6)
        self.checkBox_7 = QtGui.QCheckBox(self.widget4)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.verticalLayout_6.addWidget(self.checkBox_7)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.checkBox_5 = QtGui.QCheckBox(self.widget4)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.horizontalLayout_11.addWidget(self.checkBox_5)
        self.spinBox_9 = QtGui.QSpinBox(self.widget4)
        self.spinBox_9.setObjectName(_fromUtf8("spinBox_9"))
        self.horizontalLayout_11.addWidget(self.spinBox_9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.tabDcm.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_6)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 40, 581, 371))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.treeWidget_2 = QtGui.QTreeWidget(self.tab_9)
        self.treeWidget_2.setGeometry(QtCore.QRect(10, 20, 261, 311))
        self.treeWidget_2.setObjectName(_fromUtf8("treeWidget_2"))
        self.treeWidget_3 = QtGui.QTreeWidget(self.tab_9)
        self.treeWidget_3.setGeometry(QtCore.QRect(330, 20, 241, 311))
        self.treeWidget_3.setObjectName(_fromUtf8("treeWidget_3"))
        self.treeWidget_3.headerItem().setText(0, _fromUtf8("Avaliable Security level"))
        self.widget5 = QtGui.QWidget(self.tab_9)
        self.widget5.setGeometry(QtCore.QRect(280, 70, 41, 62))
        self.widget5.setObjectName(_fromUtf8("widget5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget5)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.pushButton_5 = QtGui.QPushButton(self.widget5)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.widget5)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.verticalLayout_7.addWidget(self.pushButton_6)
        self.tabWidget_2.addTab(self.tab_9, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.treeWidget_4 = QtGui.QTreeWidget(self.tab_10)
        self.treeWidget_4.setGeometry(QtCore.QRect(10, 20, 261, 311))
        self.treeWidget_4.setObjectName(_fromUtf8("treeWidget_4"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab_10)
        self.layoutWidget_2.setGeometry(QtCore.QRect(280, 70, 41, 62))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.pushButton_7 = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.verticalLayout_8.addWidget(self.pushButton_7)
        self.pushButton_8 = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.verticalLayout_8.addWidget(self.pushButton_8)
        self.treeWidget_5 = QtGui.QTreeWidget(self.tab_10)
        self.treeWidget_5.setGeometry(QtCore.QRect(330, 20, 241, 311))
        self.treeWidget_5.setObjectName(_fromUtf8("treeWidget_5"))
        self.treeWidget_5.headerItem().setText(0, _fromUtf8("Avaliable Session"))
        self.tabWidget_2.addTab(self.tab_10, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.widget6 = QtGui.QWidget(self.tab_11)
        self.widget6.setGeometry(QtCore.QRect(10, 20, 551, 128))
        self.widget6.setObjectName(_fromUtf8("widget6"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget6)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.checkBox_8 = QtGui.QCheckBox(self.widget6)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.horizontalLayout_14.addWidget(self.checkBox_8)
        self.comboBox = QtGui.QComboBox(self.widget6)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_14.addWidget(self.comboBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.checkBox_9 = QtGui.QCheckBox(self.widget6)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.horizontalLayout_15.addWidget(self.checkBox_9)
        self.comboBox_2 = QtGui.QComboBox(self.widget6)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.horizontalLayout_15.addWidget(self.comboBox_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.checkBox_10 = QtGui.QCheckBox(self.widget6)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.horizontalLayout_16.addWidget(self.checkBox_10)
        self.comboBox_3 = QtGui.QComboBox(self.widget6)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.horizontalLayout_16.addWidget(self.comboBox_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.checkBox_11 = QtGui.QCheckBox(self.widget6)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.horizontalLayout_17.addWidget(self.checkBox_11)
        self.comboBox_4 = QtGui.QComboBox(self.widget6)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.horizontalLayout_17.addWidget(self.comboBox_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.tabWidget_2.addTab(self.tab_11, _fromUtf8(""))
        self.widget7 = QtGui.QWidget(self.tab_6)
        self.widget7.setGeometry(QtCore.QRect(10, 10, 237, 27))
        self.widget7.setObjectName(_fromUtf8("widget7"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.widget7)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_12 = QtGui.QLabel(self.widget7)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_13.addWidget(self.label_12)
        self.lineEdit_3 = QtGui.QLineEdit(self.widget7)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_13.addWidget(self.lineEdit_3)
        self.tabDcm.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_7)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 40, 581, 371))
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.treeWidget_6 = QtGui.QTreeWidget(self.tab_12)
        self.treeWidget_6.setGeometry(QtCore.QRect(10, 20, 261, 311))
        self.treeWidget_6.setObjectName(_fromUtf8("treeWidget_6"))
        self.treeWidget_7 = QtGui.QTreeWidget(self.tab_12)
        self.treeWidget_7.setGeometry(QtCore.QRect(330, 20, 241, 311))
        self.treeWidget_7.setObjectName(_fromUtf8("treeWidget_7"))
        self.treeWidget_7.headerItem().setText(0, _fromUtf8("Avaliable Security level"))
        self.layoutWidget_8 = QtGui.QWidget(self.tab_12)
        self.layoutWidget_8.setGeometry(QtCore.QRect(280, 70, 41, 62))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.pushButton_9 = QtGui.QPushButton(self.layoutWidget_8)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.verticalLayout_10.addWidget(self.pushButton_9)
        self.pushButton_10 = QtGui.QPushButton(self.layoutWidget_8)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.verticalLayout_10.addWidget(self.pushButton_10)
        self.tabWidget_3.addTab(self.tab_12, _fromUtf8(""))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.treeWidget_8 = QtGui.QTreeWidget(self.tab_13)
        self.treeWidget_8.setGeometry(QtCore.QRect(10, 20, 261, 311))
        self.treeWidget_8.setObjectName(_fromUtf8("treeWidget_8"))
        self.layoutWidget_9 = QtGui.QWidget(self.tab_13)
        self.layoutWidget_9.setGeometry(QtCore.QRect(280, 70, 41, 62))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.pushButton_11 = QtGui.QPushButton(self.layoutWidget_9)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.verticalLayout_11.addWidget(self.pushButton_11)
        self.pushButton_12 = QtGui.QPushButton(self.layoutWidget_9)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.verticalLayout_11.addWidget(self.pushButton_12)
        self.treeWidget_9 = QtGui.QTreeWidget(self.tab_13)
        self.treeWidget_9.setGeometry(QtCore.QRect(330, 20, 241, 311))
        self.treeWidget_9.setObjectName(_fromUtf8("treeWidget_9"))
        self.treeWidget_9.headerItem().setText(0, _fromUtf8("Avaliable Session"))
        self.tabWidget_3.addTab(self.tab_13, _fromUtf8(""))
        self.layoutWidget_11 = QtGui.QWidget(self.tab_7)
        self.layoutWidget_11.setGeometry(QtCore.QRect(10, 10, 237, 27))
        self.layoutWidget_11.setObjectName(_fromUtf8("layoutWidget_11"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_22.setMargin(0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_13 = QtGui.QLabel(self.layoutWidget_11)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_22.addWidget(self.label_13)
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget_11)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_22.addWidget(self.lineEdit_4)
        self.tabDcm.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.layoutWidget_12 = QtGui.QWidget(self.tab_8)
        self.layoutWidget_12.setGeometry(QtCore.QRect(10, 10, 237, 27))
        self.layoutWidget_12.setObjectName(_fromUtf8("layoutWidget_12"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.layoutWidget_12)
        self.horizontalLayout_23.setMargin(0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_14 = QtGui.QLabel(self.layoutWidget_12)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_23.addWidget(self.label_14)
        self.lineEdit_5 = QtGui.QLineEdit(self.layoutWidget_12)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_23.addWidget(self.lineEdit_5)
        self.tabWidget_4 = QtGui.QTabWidget(self.tab_8)
        self.tabWidget_4.setGeometry(QtCore.QRect(10, 40, 581, 371))
        self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
        self.tab_14 = QtGui.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.treeWidget_10 = QtGui.QTreeWidget(self.tab_14)
        self.treeWidget_10.setGeometry(QtCore.QRect(10, 20, 261, 311))
        self.treeWidget_10.setObjectName(_fromUtf8("treeWidget_10"))
        self.treeWidget_11 = QtGui.QTreeWidget(self.tab_14)
        self.treeWidget_11.setGeometry(QtCore.QRect(330, 20, 241, 311))
        self.treeWidget_11.setObjectName(_fromUtf8("treeWidget_11"))
        self.treeWidget_11.headerItem().setText(0, _fromUtf8("Avaliable Security level"))
        self.layoutWidget_10 = QtGui.QWidget(self.tab_14)
        self.layoutWidget_10.setGeometry(QtCore.QRect(280, 70, 77, 62))
        self.layoutWidget_10.setObjectName(_fromUtf8("layoutWidget_10"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.pushButton_13 = QtGui.QPushButton(self.layoutWidget_10)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.verticalLayout_12.addWidget(self.pushButton_13)
        self.pushButton_14 = QtGui.QPushButton(self.layoutWidget_10)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.verticalLayout_12.addWidget(self.pushButton_14)
        self.tabWidget_4.addTab(self.tab_14, _fromUtf8(""))
        self.tab_15 = QtGui.QWidget()
        self.tab_15.setObjectName(_fromUtf8("tab_15"))
        self.treeWidget_12 = QtGui.QTreeWidget(self.tab_15)
        self.treeWidget_12.setGeometry(QtCore.QRect(10, 20, 261, 311))
        self.treeWidget_12.setObjectName(_fromUtf8("treeWidget_12"))
        self.layoutWidget_13 = QtGui.QWidget(self.tab_15)
        self.layoutWidget_13.setGeometry(QtCore.QRect(280, 70, 77, 62))
        self.layoutWidget_13.setObjectName(_fromUtf8("layoutWidget_13"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.layoutWidget_13)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.pushButton_15 = QtGui.QPushButton(self.layoutWidget_13)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.verticalLayout_13.addWidget(self.pushButton_15)
        self.pushButton_16 = QtGui.QPushButton(self.layoutWidget_13)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.verticalLayout_13.addWidget(self.pushButton_16)
        self.treeWidget_13 = QtGui.QTreeWidget(self.tab_15)
        self.treeWidget_13.setGeometry(QtCore.QRect(330, 20, 241, 311))
        self.treeWidget_13.setObjectName(_fromUtf8("treeWidget_13"))
        self.treeWidget_13.headerItem().setText(0, _fromUtf8("Avaliable Session"))
        self.tabWidget_4.addTab(self.tab_15, _fromUtf8(""))
        self.tabDcm.addTab(self.tab_8, _fromUtf8(""))
        self.widget8 = QtGui.QWidget(self.groupBox_2)
        self.widget8.setGeometry(QtCore.QRect(290, 60, 131, 128))
        self.widget8.setObjectName(_fromUtf8("widget8"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget8)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton = QtGui.QPushButton(self.widget8)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_4.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.widget8)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.widget8)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.widget8)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout_4.addWidget(self.pushButton_4)

        self.retranslateUi(cd_dcm)
        self.tabWidget.setCurrentIndex(0)
        self.tabDcm.setCurrentIndex(3)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(cd_dcm)

    def retranslateUi(self, cd_dcm):
        cd_dcm.setWindowTitle(QtGui.QApplication.translate("cd_dcm", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("cd_dcm", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("cd_dcm", "Development Error Detection", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("cd_dcm", "MainFunction Period:", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox.setToolTip(QtGui.QApplication.translate("cd_dcm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">in uint (ms)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("cd_dcm", "Respond All Request", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("cd_dcm", "Verdion Info API", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("cd_dcm", "Response Pending", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("cd_dcm", "Max Negative Response", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("cd_dcm", "Response Pending Handling", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("cd_dcm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Max Number of Simultaneous</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Periodic transmissions:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("cd_dcm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Periodic transmission Slow:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("cd_dcm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Periodic transmission</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Medium:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("cd_dcm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Periodic transmission Fast:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("cd_dcm", "Periodic Transmission", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("cd_dcm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Max Sources for One </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Dynamic Identifier:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("cd_dcm", "Dynamic Identifiers", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("cd_dcm", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("cd_dcm", "Dcm Object", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("cd_dcm", "Buffers", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("cd_dcm", "Did Infos", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(2).setText(0, QtGui.QApplication.translate("cd_dcm", "DIDs", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(3).setText(0, QtGui.QApplication.translate("cd_dcm", "Memory", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(4).setText(0, QtGui.QApplication.translate("cd_dcm", "Protocols", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(5).setText(0, QtGui.QApplication.translate("cd_dcm", "Request Services", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(6).setText(0, QtGui.QApplication.translate("cd_dcm", "Routine Infos", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(7).setText(0, QtGui.QApplication.translate("cd_dcm", "Routines", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(8).setText(0, QtGui.QApplication.translate("cd_dcm", "Security Levels", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(9).setText(0, QtGui.QApplication.translate("cd_dcm", "Service Tables", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(10).setText(0, QtGui.QApplication.translate("cd_dcm", "Seeion Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(11).setText(0, QtGui.QApplication.translate("cd_dcm", "Sessions", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(12).setText(0, QtGui.QApplication.translate("cd_dcm", "Timings", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(QtGui.QApplication.translate("cd_dcm", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("cd_dcm", "Size(Byte):", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDcm.setTabText(self.tabDcm.indexOf(self.tab_4), QtGui.QApplication.translate("cd_dcm", "Buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("cd_dcm", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("cd_dcm", "Fixed length", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("cd_dcm", "Dynamically defined", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("cd_dcm", "Scaling info size:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDcm.setTabText(self.tabDcm.indexOf(self.tab_5), QtGui.QApplication.translate("cd_dcm", "Did Info", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(0, QtGui.QApplication.translate("cd_dcm", "Security level", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("cd_dcm", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("cd_dcm", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), QtGui.QApplication.translate("cd_dcm", "Security level", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_4.headerItem().setText(0, QtGui.QApplication.translate("cd_dcm", "Session", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("cd_dcm", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("cd_dcm", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), QtGui.QApplication.translate("cd_dcm", "Session", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("cd_dcm", "Freeze Current State Ref:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setText(QtGui.QApplication.translate("cd_dcm", "Reset to Default Ref:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_10.setText(QtGui.QApplication.translate("cd_dcm", "Return Control to Ecu Ref", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_11.setText(QtGui.QApplication.translate("cd_dcm", "Short Term Adjustement Ref", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), QtGui.QApplication.translate("cd_dcm", "Misc", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("cd_dcm", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDcm.setTabText(self.tabDcm.indexOf(self.tab_6), QtGui.QApplication.translate("cd_dcm", "Did Control", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_6.headerItem().setText(0, QtGui.QApplication.translate("cd_dcm", "Security level", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("cd_dcm", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("cd_dcm", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), QtGui.QApplication.translate("cd_dcm", "Security level", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_8.headerItem().setText(0, QtGui.QApplication.translate("cd_dcm", "Session", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("cd_dcm", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("cd_dcm", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), QtGui.QApplication.translate("cd_dcm", "Session", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("cd_dcm", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDcm.setTabText(self.tabDcm.indexOf(self.tab_7), QtGui.QApplication.translate("cd_dcm", "Did Read", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("cd_dcm", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_10.headerItem().setText(0, QtGui.QApplication.translate("cd_dcm", "Security level", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("cd_dcm", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_14.setText(QtGui.QApplication.translate("cd_dcm", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_14), QtGui.QApplication.translate("cd_dcm", "Security level", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_12.headerItem().setText(0, QtGui.QApplication.translate("cd_dcm", "Session", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_15.setText(QtGui.QApplication.translate("cd_dcm", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_16.setText(QtGui.QApplication.translate("cd_dcm", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_15), QtGui.QApplication.translate("cd_dcm", "Session", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDcm.setTabText(self.tabDcm.indexOf(self.tab_8), QtGui.QApplication.translate("cd_dcm", "Did Write", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("cd_dcm", "add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("cd_dcm", "add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("cd_dcm", "add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("cd_dcm", "add", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    cd_dcm = QtGui.QDialog()
    ui = Ui_cd_dcm()
    ui.setupUi(cd_dcm)
    cd_dcm.show()
    sys.exit(app.exec_())

