# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\parai@foxmail.com\github\gainos-tk\tool\gainos-studio\ui\forms\cd_cannm.ui'
#
# Created: Fri Jun 14 22:32:20 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_cd_cannm(object):
    def setupUi(self, cd_cannm):
        cd_cannm.setObjectName(_fromUtf8("cd_cannm"))
        cd_cannm.resize(962, 512)
        cd_cannm.setStyleSheet(_fromUtf8("font: 12pt \"Consolas\";"))
        self.groupBox = QtGui.QGroupBox(cd_cannm)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 951, 101))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 50, 533, 25))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cbxDevErr = QtGui.QCheckBox(self.layoutWidget)
        self.cbxDevErr.setObjectName(_fromUtf8("cbxDevErr"))
        self.horizontalLayout.addWidget(self.cbxDevErr)
        self.cbxVersionInfoApi = QtGui.QCheckBox(self.layoutWidget)
        self.cbxVersionInfoApi.setObjectName(_fromUtf8("cbxVersionInfoApi"))
        self.horizontalLayout.addWidget(self.cbxVersionInfoApi)
        self.cbxPassiveModeEn = QtGui.QCheckBox(self.layoutWidget)
        self.cbxPassiveModeEn.setObjectName(_fromUtf8("cbxPassiveModeEn"))
        self.horizontalLayout.addWidget(self.cbxPassiveModeEn)
        self.groupBox_2 = QtGui.QGroupBox(cd_cannm)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 951, 401))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.tabCfg = QtGui.QTabWidget(self.groupBox_2)
        self.tabCfg.setGeometry(QtCore.QRect(420, 10, 531, 381))
        self.tabCfg.setObjectName(_fromUtf8("tabCfg"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget = QtGui.QTabWidget(self.tab_3)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 511, 321))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget1 = QtGui.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 491, 161))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_44 = QtGui.QLabel(self.layoutWidget1)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_15.addWidget(self.label_44)
        self.leChanneName = QtGui.QLineEdit(self.layoutWidget1)
        self.leChanneName.setText(_fromUtf8(""))
        self.leChanneName.setObjectName(_fromUtf8("leChanneName"))
        self.horizontalLayout_15.addWidget(self.leChanneName)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.spbxMainFncPeriod = QtGui.QSpinBox(self.layoutWidget1)
        self.spbxMainFncPeriod.setMinimumSize(QtCore.QSize(200, 0))
        self.spbxMainFncPeriod.setMaximum(65535)
        self.spbxMainFncPeriod.setObjectName(_fromUtf8("spbxMainFncPeriod"))
        self.horizontalLayout_5.addWidget(self.spbxMainFncPeriod)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_47 = QtGui.QLabel(self.layoutWidget1)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_22.addWidget(self.label_47)
        self.leNodeId = QtGui.QLineEdit(self.layoutWidget1)
        self.leNodeId.setText(_fromUtf8(""))
        self.leNodeId.setObjectName(_fromUtf8("leNodeId"))
        self.horizontalLayout_22.addWidget(self.leNodeId)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_30 = QtGui.QLabel(self.layoutWidget1)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_6.addWidget(self.label_30)
        self.cmbxNetworkHandle = QtGui.QComboBox(self.layoutWidget1)
        self.cmbxNetworkHandle.setEnabled(False)
        self.cmbxNetworkHandle.setMinimumSize(QtCore.QSize(300, 0))
        self.cmbxNetworkHandle.setToolTip(_fromUtf8(""))
        self.cmbxNetworkHandle.setObjectName(_fromUtf8("cmbxNetworkHandle"))
        self.horizontalLayout_6.addWidget(self.cmbxNetworkHandle)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_32 = QtGui.QLabel(self.layoutWidget1)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_16.addWidget(self.label_32)
        self.cmbxNmChannel = QtGui.QComboBox(self.layoutWidget1)
        self.cmbxNmChannel.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbxNmChannel.setObjectName(_fromUtf8("cmbxNmChannel"))
        self.horizontalLayout_16.addWidget(self.cmbxNmChannel)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget2 = QtGui.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 491, 124))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.cbxChlActive = QtGui.QCheckBox(self.layoutWidget2)
        self.cbxChlActive.setObjectName(_fromUtf8("cbxChlActive"))
        self.verticalLayout_2.addWidget(self.cbxChlActive)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.spbxRepeatMessageTime = QtGui.QSpinBox(self.layoutWidget2)
        self.spbxRepeatMessageTime.setMinimumSize(QtCore.QSize(200, 0))
        self.spbxRepeatMessageTime.setMaximum(65535)
        self.spbxRepeatMessageTime.setObjectName(_fromUtf8("spbxRepeatMessageTime"))
        self.horizontalLayout_7.addWidget(self.spbxRepeatMessageTime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_8.addWidget(self.label_4)
        self.spbxPrepareBusSleepTime = QtGui.QSpinBox(self.layoutWidget2)
        self.spbxPrepareBusSleepTime.setMinimumSize(QtCore.QSize(200, 0))
        self.spbxPrepareBusSleepTime.setMaximum(65535)
        self.spbxPrepareBusSleepTime.setObjectName(_fromUtf8("spbxPrepareBusSleepTime"))
        self.horizontalLayout_8.addWidget(self.spbxPrepareBusSleepTime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_9.addWidget(self.label_5)
        self.spbxTimeoutTime = QtGui.QSpinBox(self.layoutWidget2)
        self.spbxTimeoutTime.setMinimumSize(QtCore.QSize(200, 0))
        self.spbxTimeoutTime.setMaximum(65535)
        self.spbxTimeoutTime.setObjectName(_fromUtf8("spbxTimeoutTime"))
        self.horizontalLayout_9.addWidget(self.spbxTimeoutTime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.layoutWidget3 = QtGui.QWidget(self.tab_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 481, 244))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_33 = QtGui.QLabel(self.layoutWidget3)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_17.addWidget(self.label_33)
        self.cmbxTxPdu = QtGui.QComboBox(self.layoutWidget3)
        self.cmbxTxPdu.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbxTxPdu.setObjectName(_fromUtf8("cmbxTxPdu"))
        self.horizontalLayout_17.addWidget(self.cmbxTxPdu)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_34 = QtGui.QLabel(self.layoutWidget3)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_18.addWidget(self.label_34)
        self.cmbxRxPdu = QtGui.QComboBox(self.layoutWidget3)
        self.cmbxRxPdu.setEnabled(True)
        self.cmbxRxPdu.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbxRxPdu.setObjectName(_fromUtf8("cmbxRxPdu"))
        self.horizontalLayout_18.addWidget(self.cmbxRxPdu)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_6 = QtGui.QLabel(self.layoutWidget3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_10.addWidget(self.label_6)
        self.spbxTxCycleTime = QtGui.QSpinBox(self.layoutWidget3)
        self.spbxTxCycleTime.setMinimumSize(QtCore.QSize(200, 0))
        self.spbxTxCycleTime.setMaximum(65535)
        self.spbxTxCycleTime.setObjectName(_fromUtf8("spbxTxCycleTime"))
        self.horizontalLayout_10.addWidget(self.spbxTxCycleTime)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_7 = QtGui.QLabel(self.layoutWidget3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_11.addWidget(self.label_7)
        self.spbxTxCycleTimeOffset = QtGui.QSpinBox(self.layoutWidget3)
        self.spbxTxCycleTimeOffset.setMinimumSize(QtCore.QSize(200, 0))
        self.spbxTxCycleTimeOffset.setMaximum(65535)
        self.spbxTxCycleTimeOffset.setObjectName(_fromUtf8("spbxTxCycleTimeOffset"))
        self.horizontalLayout_11.addWidget(self.spbxTxCycleTimeOffset)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_35 = QtGui.QLabel(self.layoutWidget3)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_2.addWidget(self.label_35)
        self.cmbxCBVPosition = QtGui.QComboBox(self.layoutWidget3)
        self.cmbxCBVPosition.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbxCBVPosition.setObjectName(_fromUtf8("cmbxCBVPosition"))
        self.cmbxCBVPosition.addItem(_fromUtf8(""))
        self.cmbxCBVPosition.addItem(_fromUtf8(""))
        self.cmbxCBVPosition.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmbxCBVPosition)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_36 = QtGui.QLabel(self.layoutWidget3)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_20.addWidget(self.label_36)
        self.cmbxNodeIdPosition = QtGui.QComboBox(self.layoutWidget3)
        self.cmbxNodeIdPosition.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbxNodeIdPosition.setObjectName(_fromUtf8("cmbxNodeIdPosition"))
        self.cmbxNodeIdPosition.addItem(_fromUtf8(""))
        self.cmbxNodeIdPosition.addItem(_fromUtf8(""))
        self.cmbxNodeIdPosition.addItem(_fromUtf8(""))
        self.horizontalLayout_20.addWidget(self.cmbxNodeIdPosition)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_8 = QtGui.QLabel(self.layoutWidget3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_12.addWidget(self.label_8)
        self.spbxPduLength = QtGui.QSpinBox(self.layoutWidget3)
        self.spbxPduLength.setMinimumSize(QtCore.QSize(200, 0))
        self.spbxPduLength.setToolTip(_fromUtf8(""))
        self.spbxPduLength.setObjectName(_fromUtf8("spbxPduLength"))
        self.horizontalLayout_12.addWidget(self.spbxPduLength)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tabCfg.addTab(self.tab_3, _fromUtf8(""))
        self.btn1 = QtGui.QPushButton(self.groupBox_2)
        self.btn1.setGeometry(QtCore.QRect(291, 55, 111, 23))
        self.btn1.setObjectName(_fromUtf8("btn1"))
        self.trCanNmCfg = QtGui.QTreeWidget(self.groupBox_2)
        self.trCanNmCfg.setGeometry(QtCore.QRect(10, 30, 256, 361))
        self.trCanNmCfg.setObjectName(_fromUtf8("trCanNmCfg"))
        item_0 = QtGui.QTreeWidgetItem(self.trCanNmCfg)

        self.retranslateUi(cd_cannm)
        self.tabCfg.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(cd_cannm)

    def retranslateUi(self, cd_cannm):
        cd_cannm.setWindowTitle(QtGui.QApplication.translate("cd_cannm", "Can Network Management", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("cd_cannm", "CanNm General", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxDevErr.setText(QtGui.QApplication.translate("cd_cannm", "DevErrorDetection", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxVersionInfoApi.setText(QtGui.QApplication.translate("cd_cannm", "VersionInfoApi", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxPassiveModeEn.setText(QtGui.QApplication.translate("cd_cannm", "Passive Mode Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("cd_cannm", "CanNm Entities", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("cd_cannm", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("cd_cannm", "Main Function Period:", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxMainFncPeriod.setToolTip(QtGui.QApplication.translate("cd_cannm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ms</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("cd_cannm", "Node Id:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("cd_cannm", "Network Handle:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("cd_cannm", "Nm Channel:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxNmChannel.setToolTip(QtGui.QApplication.translate("cd_cannm", "Only Physical is allowed Now!", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("cd_cannm", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxChlActive.setText(QtGui.QApplication.translate("cd_cannm", "Channel Active", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("cd_cannm", "Repeat Message Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxRepeatMessageTime.setToolTip(QtGui.QApplication.translate("cd_cannm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ms</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("cd_cannm", "Prepare Bus Sleep Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxPrepareBusSleepTime.setToolTip(QtGui.QApplication.translate("cd_cannm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ms</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("cd_cannm", "Network Mode Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxTimeoutTime.setToolTip(QtGui.QApplication.translate("cd_cannm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TimeoutTime(ms)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("cd_cannm", "State Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("cd_cannm", "Tx Pdu:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxTxPdu.setToolTip(QtGui.QApplication.translate("cd_cannm", "Only Physical is allowed Now!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("cd_cannm", "Rx Pdu:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxRxPdu.setToolTip(QtGui.QApplication.translate("cd_cannm", "Only Physical is allowed Now!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("cd_cannm", "Tx Cycle Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxTxCycleTime.setToolTip(QtGui.QApplication.translate("cd_cannm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ms</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("cd_cannm", "Tx Cycle Time Offset:", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxTxCycleTimeOffset.setToolTip(QtGui.QApplication.translate("cd_cannm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ms</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("cd_cannm", "Control Bit \n"
"Vector Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxCBVPosition.setToolTip(QtGui.QApplication.translate("cd_cannm", "Only Physical is allowed Now!", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxCBVPosition.setItemText(0, QtGui.QApplication.translate("cd_cannm", "CANNM_PDU_BYTE_0", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxCBVPosition.setItemText(1, QtGui.QApplication.translate("cd_cannm", "CANNM_PDU_BYTE_1", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxCBVPosition.setItemText(2, QtGui.QApplication.translate("cd_cannm", "CANNM_PDU_OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("cd_cannm", "Node Id Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxNodeIdPosition.setToolTip(QtGui.QApplication.translate("cd_cannm", "Only Physical is allowed Now!", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxNodeIdPosition.setItemText(0, QtGui.QApplication.translate("cd_cannm", "CANNM_PDU_BYTE_0", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxNodeIdPosition.setItemText(1, QtGui.QApplication.translate("cd_cannm", "CANNM_PDU_BYTE_1", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxNodeIdPosition.setItemText(2, QtGui.QApplication.translate("cd_cannm", "CANNM_PDU_OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("cd_cannm", "Pdu Length(byte):", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("cd_cannm", "Message", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCfg.setTabText(self.tabCfg.indexOf(self.tab_3), QtGui.QApplication.translate("cd_cannm", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.btn1.setText(QtGui.QApplication.translate("cd_cannm", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.trCanNmCfg.headerItem().setText(0, QtGui.QApplication.translate("cd_cannm", "CanNm", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.trCanNmCfg.isSortingEnabled()
        self.trCanNmCfg.setSortingEnabled(False)
        self.trCanNmCfg.topLevelItem(0).setText(0, QtGui.QApplication.translate("cd_cannm", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.trCanNmCfg.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    cd_cannm = QtGui.QDialog()
    ui = Ui_cd_cannm()
    ui.setupUi(cd_cannm)
    cd_cannm.show()
    sys.exit(app.exec_())

