# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\parai@foxmail.com\github\gainos-tk\tool\gainos-studio\ui\forms\cd_pdur.ui'
#
# Created: Tue May 14 19:56:48 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_cd_pdur(object):
    def setupUi(self, cd_pdur):
        cd_pdur.setObjectName(_fromUtf8("cd_pdur"))
        cd_pdur.resize(1086, 586)
        self.groupBox_2 = QtGui.QGroupBox(cd_pdur)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 170, 1061, 411))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.trPduRCfg = QtGui.QTreeWidget(self.groupBox_2)
        self.trPduRCfg.setGeometry(QtCore.QRect(20, 30, 361, 371))
        self.trPduRCfg.setObjectName(_fromUtf8("trPduRCfg"))
        item_0 = QtGui.QTreeWidgetItem(self.trPduRCfg)
        item_0 = QtGui.QTreeWidgetItem(self.trPduRCfg)
        self.tabCfg = QtGui.QTabWidget(self.groupBox_2)
        self.tabCfg.setGeometry(QtCore.QRect(550, 20, 491, 381))
        self.tabCfg.setMaximumSize(QtCore.QSize(16777215, 16777214))
        self.tabCfg.setObjectName(_fromUtf8("tabCfg"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 461, 108))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.leSrcName = QtGui.QLineEdit(self.layoutWidget)
        self.leSrcName.setObjectName(_fromUtf8("leSrcName"))
        self.horizontalLayout_2.addWidget(self.leSrcName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spbxSduLength = QtGui.QSpinBox(self.layoutWidget)
        self.spbxSduLength.setObjectName(_fromUtf8("spbxSduLength"))
        self.horizontalLayout_3.addWidget(self.spbxSduLength)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.cmbxSrcPdu = QtGui.QComboBox(self.layoutWidget)
        self.cmbxSrcPdu.setObjectName(_fromUtf8("cmbxSrcPdu"))
        self.horizontalLayout_4.addWidget(self.cmbxSrcPdu)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.cbxSrcModule = QtGui.QCheckBox(self.layoutWidget)
        self.cbxSrcModule.setObjectName(_fromUtf8("cbxSrcModule"))
        self.horizontalLayout_5.addWidget(self.cbxSrcModule)
        self.cmbxSrcModule = QtGui.QComboBox(self.layoutWidget)
        self.cmbxSrcModule.setObjectName(_fromUtf8("cmbxSrcModule"))
        self.cmbxSrcModule.addItem(_fromUtf8(""))
        self.cmbxSrcModule.addItem(_fromUtf8(""))
        self.cmbxSrcModule.addItem(_fromUtf8(""))
        self.cmbxSrcModule.addItem(_fromUtf8(""))
        self.cmbxSrcModule.addItem(_fromUtf8(""))
        self.cmbxSrcModule.addItem(_fromUtf8(""))
        self.cmbxSrcModule.addItem(_fromUtf8(""))
        self.cmbxSrcModule.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.cmbxSrcModule)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.tabCfg.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 461, 108))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.leDstName = QtGui.QLineEdit(self.layoutWidget1)
        self.leDstName.setObjectName(_fromUtf8("leDstName"))
        self.horizontalLayout_6.addWidget(self.leDstName)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.cbxDataProvision = QtGui.QCheckBox(self.layoutWidget1)
        self.cbxDataProvision.setObjectName(_fromUtf8("cbxDataProvision"))
        self.horizontalLayout_7.addWidget(self.cbxDataProvision)
        self.cmbxDataProvision = QtGui.QComboBox(self.layoutWidget1)
        self.cmbxDataProvision.setObjectName(_fromUtf8("cmbxDataProvision"))
        self.cmbxDataProvision.addItem(_fromUtf8(""))
        self.cmbxDataProvision.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.cmbxDataProvision)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.cmbxDstPdu = QtGui.QComboBox(self.layoutWidget1)
        self.cmbxDstPdu.setObjectName(_fromUtf8("cmbxDstPdu"))
        self.horizontalLayout_8.addWidget(self.cmbxDstPdu)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.cbxDstModule = QtGui.QCheckBox(self.layoutWidget1)
        self.cbxDstModule.setObjectName(_fromUtf8("cbxDstModule"))
        self.horizontalLayout_9.addWidget(self.cbxDstModule)
        self.cmbxDstModule = QtGui.QComboBox(self.layoutWidget1)
        self.cmbxDstModule.setObjectName(_fromUtf8("cmbxDstModule"))
        self.cmbxDstModule.addItem(_fromUtf8(""))
        self.cmbxDstModule.addItem(_fromUtf8(""))
        self.cmbxDstModule.addItem(_fromUtf8(""))
        self.cmbxDstModule.addItem(_fromUtf8(""))
        self.cmbxDstModule.addItem(_fromUtf8(""))
        self.cmbxDstModule.addItem(_fromUtf8(""))
        self.cmbxDstModule.addItem(_fromUtf8(""))
        self.cmbxDstModule.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.cmbxDstModule)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.tabCfg.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.layoutWidget2 = QtGui.QWidget(self.tab_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 31, 461, 52))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_10.addWidget(self.label_5)
        self.leBufferName = QtGui.QLineEdit(self.layoutWidget2)
        self.leBufferName.setObjectName(_fromUtf8("leBufferName"))
        self.horizontalLayout_10.addWidget(self.leBufferName)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_7 = QtGui.QLabel(self.layoutWidget2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_11.addWidget(self.label_7)
        self.spbxBufferSize = QtGui.QSpinBox(self.layoutWidget2)
        self.spbxBufferSize.setObjectName(_fromUtf8("spbxBufferSize"))
        self.horizontalLayout_11.addWidget(self.spbxBufferSize)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.tabCfg.addTab(self.tab_3, _fromUtf8(""))
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(400, 55, 131, 54))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.btnAdd = QtGui.QPushButton(self.layoutWidget3)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.verticalLayout_2.addWidget(self.btnAdd)
        self.btnDel = QtGui.QPushButton(self.layoutWidget3)
        self.btnDel.setObjectName(_fromUtf8("btnDel"))
        self.verticalLayout_2.addWidget(self.btnDel)
        self.groupBox = QtGui.QGroupBox(cd_pdur)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 441, 151))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget4 = QtGui.QWidget(self.groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 20, 211, 62))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.cbxDevErr = QtGui.QCheckBox(self.layoutWidget4)
        self.cbxDevErr.setObjectName(_fromUtf8("cbxDevErr"))
        self.verticalLayout_10.addWidget(self.cbxDevErr)
        self.cbxVersionInfo = QtGui.QCheckBox(self.layoutWidget4)
        self.cbxVersionInfo.setObjectName(_fromUtf8("cbxVersionInfo"))
        self.verticalLayout_10.addWidget(self.cbxVersionInfo)
        self.cbxZeroCostEnable = QtGui.QCheckBox(self.layoutWidget4)
        self.cbxZeroCostEnable.setObjectName(_fromUtf8("cbxZeroCostEnable"))
        self.verticalLayout_10.addWidget(self.cbxZeroCostEnable)
        self.layoutWidget5 = QtGui.QWidget(self.groupBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 90, 167, 52))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.cbxSingleIf = QtGui.QCheckBox(self.layoutWidget5)
        self.cbxSingleIf.setObjectName(_fromUtf8("cbxSingleIf"))
        self.horizontalLayout_16.addWidget(self.cbxSingleIf)
        self.cmbxSingleIf = QtGui.QComboBox(self.layoutWidget5)
        self.cmbxSingleIf.setObjectName(_fromUtf8("cmbxSingleIf"))
        self.cmbxSingleIf.addItem(_fromUtf8(""))
        self.cmbxSingleIf.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.cmbxSingleIf)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.cbxSingleTp = QtGui.QCheckBox(self.layoutWidget5)
        self.cbxSingleTp.setObjectName(_fromUtf8("cbxSingleTp"))
        self.horizontalLayout_17.addWidget(self.cbxSingleTp)
        self.cmbxSingleTp = QtGui.QComboBox(self.layoutWidget5)
        self.cmbxSingleTp.setObjectName(_fromUtf8("cmbxSingleTp"))
        self.cmbxSingleTp.addItem(_fromUtf8(""))
        self.cmbxSingleTp.addItem(_fromUtf8(""))
        self.cmbxSingleTp.addItem(_fromUtf8(""))
        self.horizontalLayout_17.addWidget(self.cmbxSingleTp)
        self.verticalLayout_11.addLayout(self.horizontalLayout_17)
        self.groupBox_3 = QtGui.QGroupBox(cd_pdur)
        self.groupBox_3.setGeometry(QtCore.QRect(470, 10, 601, 151))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget6 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 42, 221, 86))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cbxCanIf = QtGui.QCheckBox(self.layoutWidget6)
        self.cbxCanIf.setObjectName(_fromUtf8("cbxCanIf"))
        self.verticalLayout.addWidget(self.cbxCanIf)
        self.cbxCanTp = QtGui.QCheckBox(self.layoutWidget6)
        self.cbxCanTp.setObjectName(_fromUtf8("cbxCanTp"))
        self.verticalLayout.addWidget(self.cbxCanTp)
        self.cbxCom = QtGui.QCheckBox(self.layoutWidget6)
        self.cbxCom.setObjectName(_fromUtf8("cbxCom"))
        self.verticalLayout.addWidget(self.cbxCom)
        self.cbxDcm = QtGui.QCheckBox(self.layoutWidget6)
        self.cbxDcm.setObjectName(_fromUtf8("cbxDcm"))
        self.verticalLayout.addWidget(self.cbxDcm)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.cbxLinIf = QtGui.QCheckBox(self.layoutWidget6)
        self.cbxLinIf.setObjectName(_fromUtf8("cbxLinIf"))
        self.verticalLayout_9.addWidget(self.cbxLinIf)
        self.cbxLinTp = QtGui.QCheckBox(self.layoutWidget6)
        self.cbxLinTp.setObjectName(_fromUtf8("cbxLinTp"))
        self.verticalLayout_9.addWidget(self.cbxLinTp)
        self.cbxJ1939Tp = QtGui.QCheckBox(self.layoutWidget6)
        self.cbxJ1939Tp.setObjectName(_fromUtf8("cbxJ1939Tp"))
        self.verticalLayout_9.addWidget(self.cbxJ1939Tp)
        self.horizontalLayout.addLayout(self.verticalLayout_9)

        self.retranslateUi(cd_pdur)
        self.tabCfg.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(cd_pdur)

    def retranslateUi(self, cd_pdur):
        cd_pdur.setWindowTitle(QtGui.QApplication.translate("cd_pdur", "Pdu Router", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("cd_pdur", "PduR Entities", None, QtGui.QApplication.UnicodeUTF8))
        self.trPduRCfg.headerItem().setText(0, QtGui.QApplication.translate("cd_pdur", "PduR", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.trPduRCfg.isSortingEnabled()
        self.trPduRCfg.setSortingEnabled(False)
        self.trPduRCfg.topLevelItem(0).setText(0, QtGui.QApplication.translate("cd_pdur", "Routing Table", None, QtGui.QApplication.UnicodeUTF8))
        self.trPduRCfg.topLevelItem(1).setText(0, QtGui.QApplication.translate("cd_pdur", "Tp Buffers", None, QtGui.QApplication.UnicodeUTF8))
        self.trPduRCfg.setSortingEnabled(__sortingEnabled)
        self.label.setText(QtGui.QApplication.translate("cd_pdur", "Symbolic Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("cd_pdur", "Sdu Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("cd_pdur", "Source Pdu:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSrcModule.setText(QtGui.QApplication.translate("cd_pdur", "Overriden Source Module:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSrcModule.setItemText(0, QtGui.QApplication.translate("cd_pdur", "Com", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSrcModule.setItemText(1, QtGui.QApplication.translate("cd_pdur", "Dcm", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSrcModule.setItemText(2, QtGui.QApplication.translate("cd_pdur", "CanIf", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSrcModule.setItemText(3, QtGui.QApplication.translate("cd_pdur", "CanTp", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSrcModule.setItemText(4, QtGui.QApplication.translate("cd_pdur", "LinIf", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSrcModule.setItemText(5, QtGui.QApplication.translate("cd_pdur", "LinTp", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSrcModule.setItemText(6, QtGui.QApplication.translate("cd_pdur", "FrIf", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSrcModule.setItemText(7, QtGui.QApplication.translate("cd_pdur", "FrTp", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCfg.setTabText(self.tabCfg.indexOf(self.tab), QtGui.QApplication.translate("cd_pdur", "Routing Path Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("cd_pdur", "Symbolic Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxDataProvision.setText(QtGui.QApplication.translate("cd_pdur", "Data Provision", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxDataProvision.setItemText(0, QtGui.QApplication.translate("cd_pdur", "DIRECT", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxDataProvision.setItemText(1, QtGui.QApplication.translate("cd_pdur", "TRIGGER_TRANSMIT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("cd_pdur", "Destination Pdu:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxDstModule.setText(QtGui.QApplication.translate("cd_pdur", "Overriden Destinatione Module:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxDstModule.setItemText(0, QtGui.QApplication.translate("cd_pdur", "Com", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxDstModule.setItemText(1, QtGui.QApplication.translate("cd_pdur", "Dcm", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxDstModule.setItemText(2, QtGui.QApplication.translate("cd_pdur", "CanIf", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxDstModule.setItemText(3, QtGui.QApplication.translate("cd_pdur", "CanTp", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxDstModule.setItemText(4, QtGui.QApplication.translate("cd_pdur", "LinIf", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxDstModule.setItemText(5, QtGui.QApplication.translate("cd_pdur", "LinTp", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxDstModule.setItemText(6, QtGui.QApplication.translate("cd_pdur", "FrIf", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxDstModule.setItemText(7, QtGui.QApplication.translate("cd_pdur", "FrTp", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCfg.setTabText(self.tabCfg.indexOf(self.tab_2), QtGui.QApplication.translate("cd_pdur", "Routing Path Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("cd_pdur", "Buffer Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("cd_pdur", "Buffer Size in Bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCfg.setTabText(self.tabCfg.indexOf(self.tab_3), QtGui.QApplication.translate("cd_pdur", "Tp Buffer Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("cd_pdur", "Add Routing Path", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDel.setText(QtGui.QApplication.translate("cd_pdur", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("cd_pdur", "PduR General", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxDevErr.setText(QtGui.QApplication.translate("cd_pdur", "DevErrorDetection", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxVersionInfo.setText(QtGui.QApplication.translate("cd_pdur", "VersionInfoApi", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxZeroCostEnable.setText(QtGui.QApplication.translate("cd_pdur", "Enable Zero Cost Operation Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSingleIf.setText(QtGui.QApplication.translate("cd_pdur", "Single If:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSingleIf.setItemText(0, QtGui.QApplication.translate("cd_pdur", "CAN_IF", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSingleIf.setItemText(1, QtGui.QApplication.translate("cd_pdur", "LIN_IF", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSingleTp.setText(QtGui.QApplication.translate("cd_pdur", "Single Tp:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSingleTp.setItemText(0, QtGui.QApplication.translate("cd_pdur", "CAN_TP", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSingleTp.setItemText(1, QtGui.QApplication.translate("cd_pdur", "LIN_TP", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSingleTp.setItemText(2, QtGui.QApplication.translate("cd_pdur", "J1939_TP", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("cd_pdur", "Activated Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxCanIf.setText(QtGui.QApplication.translate("cd_pdur", "CanIf", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxCanTp.setText(QtGui.QApplication.translate("cd_pdur", "CanTp", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxCom.setText(QtGui.QApplication.translate("cd_pdur", "Com", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxDcm.setText(QtGui.QApplication.translate("cd_pdur", "Dcm", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxLinIf.setText(QtGui.QApplication.translate("cd_pdur", "LinIf", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxLinTp.setText(QtGui.QApplication.translate("cd_pdur", "LinTp", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxJ1939Tp.setText(QtGui.QApplication.translate("cd_pdur", "J1939Tp", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    cd_pdur = QtGui.QDialog()
    ui = Ui_cd_pdur()
    ui.setupUi(cd_pdur)
    cd_pdur.show()
    sys.exit(app.exec_())

