# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\parai@foxmail.com\github\gainos-tk\tool\gainos-studio\ui\forms\cd_os.ui'
#
# Created: Mon Jun 24 20:23:14 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_cd_os(object):
    def setupUi(self, cd_os):
        cd_os.setObjectName(_fromUtf8("cd_os"))
        cd_os.resize(960, 623)
        cd_os.setStyleSheet(_fromUtf8("font: 12pt \"Consolas\";"))
        self.groupBox = QtGui.QGroupBox(cd_os)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 941, 171))
        self.groupBox.setStyleSheet(_fromUtf8("font: 12pt \"Consolas\";"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 68, 903, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.cmbxStatus = QtGui.QComboBox(self.layoutWidget)
        self.cmbxStatus.setMinimumSize(QtCore.QSize(201, 0))
        self.cmbxStatus.setMaximumSize(QtCore.QSize(210, 16777215))
        self.cmbxStatus.setToolTip(_fromUtf8(""))
        self.cmbxStatus.setObjectName(_fromUtf8("cmbxStatus"))
        self.cmbxStatus.addItem(_fromUtf8(""))
        self.cmbxStatus.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.cmbxStatus)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.cmbxSchedPolicy = QtGui.QComboBox(self.layoutWidget)
        self.cmbxSchedPolicy.setMinimumSize(QtCore.QSize(271, 0))
        self.cmbxSchedPolicy.setToolTip(_fromUtf8(""))
        self.cmbxSchedPolicy.setObjectName(_fromUtf8("cmbxSchedPolicy"))
        self.cmbxSchedPolicy.addItem(_fromUtf8(""))
        self.cmbxSchedPolicy.addItem(_fromUtf8(""))
        self.cmbxSchedPolicy.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.cmbxSchedPolicy)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.cbxTkExtend = QtGui.QCheckBox(self.layoutWidget)
        self.cbxTkExtend.setObjectName(_fromUtf8("cbxTkExtend"))
        self.horizontalLayout_8.addWidget(self.cbxTkExtend)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 100, 798, 25))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.cbxOsStartUpHook = QtGui.QCheckBox(self.layoutWidget1)
        self.cbxOsStartUpHook.setToolTip(_fromUtf8(""))
        self.cbxOsStartUpHook.setObjectName(_fromUtf8("cbxOsStartUpHook"))
        self.horizontalLayout_16.addWidget(self.cbxOsStartUpHook)
        self.cbxOsShutDownHook = QtGui.QCheckBox(self.layoutWidget1)
        self.cbxOsShutDownHook.setToolTip(_fromUtf8(""))
        self.cbxOsShutDownHook.setObjectName(_fromUtf8("cbxOsShutDownHook"))
        self.horizontalLayout_16.addWidget(self.cbxOsShutDownHook)
        self.cbxPreTaskHook = QtGui.QCheckBox(self.layoutWidget1)
        self.cbxPreTaskHook.setToolTip(_fromUtf8(""))
        self.cbxPreTaskHook.setObjectName(_fromUtf8("cbxPreTaskHook"))
        self.horizontalLayout_16.addWidget(self.cbxPreTaskHook)
        self.cbxPostTaskHook = QtGui.QCheckBox(self.layoutWidget1)
        self.cbxPostTaskHook.setToolTip(_fromUtf8(""))
        self.cbxPostTaskHook.setObjectName(_fromUtf8("cbxPostTaskHook"))
        self.horizontalLayout_16.addWidget(self.cbxPostTaskHook)
        self.cbxOsErrorHook = QtGui.QCheckBox(self.layoutWidget1)
        self.cbxOsErrorHook.setToolTip(_fromUtf8(""))
        self.cbxOsErrorHook.setObjectName(_fromUtf8("cbxOsErrorHook"))
        self.horizontalLayout_16.addWidget(self.cbxOsErrorHook)
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(21, 30, 772, 31))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.spbxMaxIpl = QtGui.QSpinBox(self.layoutWidget2)
        self.spbxMaxIpl.setMinimumSize(QtCore.QSize(91, 0))
        self.spbxMaxIpl.setToolTip(_fromUtf8(""))
        self.spbxMaxIpl.setObjectName(_fromUtf8("spbxMaxIpl"))
        self.horizontalLayout.addWidget(self.spbxMaxIpl)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spbxMaxPrio = QtGui.QSpinBox(self.layoutWidget2)
        self.spbxMaxPrio.setMinimumSize(QtCore.QSize(91, 0))
        self.spbxMaxPrio.setToolTip(_fromUtf8(""))
        self.spbxMaxPrio.setObjectName(_fromUtf8("spbxMaxPrio"))
        self.horizontalLayout_2.addWidget(self.spbxMaxPrio)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cmbxOSConfCls = QtGui.QComboBox(self.layoutWidget2)
        self.cmbxOSConfCls.setMinimumSize(QtCore.QSize(71, 0))
        self.cmbxOSConfCls.setToolTip(_fromUtf8(""))
        self.cmbxOSConfCls.setObjectName(_fromUtf8("cmbxOSConfCls"))
        self.cmbxOSConfCls.addItem(_fromUtf8(""))
        self.cmbxOSConfCls.addItem(_fromUtf8(""))
        self.cmbxOSConfCls.addItem(_fromUtf8(""))
        self.cmbxOSConfCls.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cmbxOSConfCls)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_4)
        self.cbxTskStkOverflowCheck = QtGui.QCheckBox(self.layoutWidget2)
        self.cbxTskStkOverflowCheck.setToolTip(_fromUtf8(""))
        self.cbxTskStkOverflowCheck.setObjectName(_fromUtf8("cbxTskStkOverflowCheck"))
        self.horizontalLayout_17.addWidget(self.cbxTskStkOverflowCheck)
        self.layoutWidget3 = QtGui.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 130, 625, 29))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_6 = QtGui.QLabel(self.layoutWidget3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_18.addWidget(self.label_6)
        self.spbxSystenStkSz = QtGui.QSpinBox(self.layoutWidget3)
        self.spbxSystenStkSz.setMinimumSize(QtCore.QSize(91, 0))
        self.spbxSystenStkSz.setToolTip(_fromUtf8(""))
        self.spbxSystenStkSz.setMinimum(32)
        self.spbxSystenStkSz.setMaximum(65535)
        self.spbxSystenStkSz.setSingleStep(4)
        self.spbxSystenStkSz.setObjectName(_fromUtf8("spbxSystenStkSz"))
        self.horizontalLayout_18.addWidget(self.spbxSystenStkSz)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_18)
        self.cbxShareSystemStack = QtGui.QCheckBox(self.layoutWidget3)
        self.cbxShareSystemStack.setObjectName(_fromUtf8("cbxShareSystemStack"))
        self.horizontalLayout_19.addWidget(self.cbxShareSystemStack)
        self.groupBox_2 = QtGui.QGroupBox(cd_os)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 190, 941, 431))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.tblGaInOsCfg = QtGui.QTabWidget(self.groupBox_2)
        self.tblGaInOsCfg.setGeometry(QtCore.QRect(450, 20, 481, 411))
        self.tblGaInOsCfg.setStyleSheet(_fromUtf8("font: 12pt \"Consolas\";"))
        self.tblGaInOsCfg.setObjectName(_fromUtf8("tblGaInOsCfg"))
        self.tabTask = QtGui.QWidget()
        self.tabTask.setObjectName(_fromUtf8("tabTask"))
        self.trTaskAppModeDst = QtGui.QTreeWidget(self.tabTask)
        self.trTaskAppModeDst.setGeometry(QtCore.QRect(10, 230, 211, 141))
        self.trTaskAppModeDst.setObjectName(_fromUtf8("trTaskAppModeDst"))
        self.trTaskAppModeSrc = QtGui.QTreeWidget(self.tabTask)
        self.trTaskAppModeSrc.setGeometry(QtCore.QRect(270, 230, 201, 141))
        self.trTaskAppModeSrc.setObjectName(_fromUtf8("trTaskAppModeSrc"))
        self.trTaskAppModeSrc.headerItem().setText(0, _fromUtf8("Available AppMode"))
        self.layoutWidget_11 = QtGui.QWidget(self.tabTask)
        self.layoutWidget_11.setGeometry(QtCore.QRect(230, 260, 31, 66))
        self.layoutWidget_11.setObjectName(_fromUtf8("layoutWidget_11"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget_11)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.btnTaskModeAdd = QtGui.QPushButton(self.layoutWidget_11)
        self.btnTaskModeAdd.setMinimumSize(QtCore.QSize(29, 0))
        self.btnTaskModeAdd.setMaximumSize(QtCore.QSize(29, 16777215))
        self.btnTaskModeAdd.setObjectName(_fromUtf8("btnTaskModeAdd"))
        self.gridLayout_8.addWidget(self.btnTaskModeAdd, 0, 0, 1, 1)
        self.btnTaskModeDel = QtGui.QPushButton(self.layoutWidget_11)
        self.btnTaskModeDel.setMaximumSize(QtCore.QSize(29, 16777215))
        self.btnTaskModeDel.setObjectName(_fromUtf8("btnTaskModeDel"))
        self.gridLayout_8.addWidget(self.btnTaskModeDel, 1, 0, 1, 1)
        self.layoutWidget4 = QtGui.QWidget(self.tabTask)
        self.layoutWidget4.setGeometry(QtCore.QRect(11, 25, 458, 192))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_5 = QtGui.QLabel(self.layoutWidget4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_14.addWidget(self.label_5)
        self.leTskName = QtGui.QLineEdit(self.layoutWidget4)
        self.leTskName.setObjectName(_fromUtf8("leTskName"))
        self.horizontalLayout_14.addWidget(self.leTskName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_8 = QtGui.QLabel(self.layoutWidget4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_13.addWidget(self.label_8)
        self.spbxTskStkSize = QtGui.QSpinBox(self.layoutWidget4)
        self.spbxTskStkSize.setMinimumSize(QtCore.QSize(250, 0))
        self.spbxTskStkSize.setToolTip(_fromUtf8(""))
        self.spbxTskStkSize.setMaximum(65535)
        self.spbxTskStkSize.setObjectName(_fromUtf8("spbxTskStkSize"))
        self.horizontalLayout_13.addWidget(self.spbxTskStkSize)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_22 = QtGui.QLabel(self.layoutWidget4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_12.addWidget(self.label_22)
        self.cmbxTskType = QtGui.QComboBox(self.layoutWidget4)
        self.cmbxTskType.setEnabled(False)
        self.cmbxTskType.setMinimumSize(QtCore.QSize(300, 0))
        self.cmbxTskType.setObjectName(_fromUtf8("cmbxTskType"))
        self.cmbxTskType.addItem(_fromUtf8(""))
        self.cmbxTskType.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.cmbxTskType)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_7 = QtGui.QLabel(self.layoutWidget4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_11.addWidget(self.label_7)
        self.spbxTskPrio = QtGui.QSpinBox(self.layoutWidget4)
        self.spbxTskPrio.setMinimumSize(QtCore.QSize(300, 0))
        self.spbxTskPrio.setObjectName(_fromUtf8("spbxTskPrio"))
        self.horizontalLayout_11.addWidget(self.spbxTskPrio)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_10 = QtGui.QLabel(self.layoutWidget4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.spbxTskMaxActivateCount = QtGui.QSpinBox(self.layoutWidget4)
        self.spbxTskMaxActivateCount.setMinimumSize(QtCore.QSize(91, 0))
        self.spbxTskMaxActivateCount.setToolTip(_fromUtf8(""))
        self.spbxTskMaxActivateCount.setMaximum(65535)
        self.spbxTskMaxActivateCount.setObjectName(_fromUtf8("spbxTskMaxActivateCount"))
        self.horizontalLayout_10.addWidget(self.spbxTskMaxActivateCount)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.cbxTskPreemtable = QtGui.QCheckBox(self.layoutWidget4)
        self.cbxTskPreemtable.setObjectName(_fromUtf8("cbxTskPreemtable"))
        self.horizontalLayout_20.addWidget(self.cbxTskPreemtable)
        self.cbxTaskAutostart = QtGui.QCheckBox(self.layoutWidget4)
        self.cbxTaskAutostart.setToolTip(_fromUtf8(""))
        self.cbxTaskAutostart.setObjectName(_fromUtf8("cbxTaskAutostart"))
        self.horizontalLayout_20.addWidget(self.cbxTaskAutostart)
        self.verticalLayout_2.addLayout(self.horizontalLayout_20)
        self.tblGaInOsCfg.addTab(self.tabTask, _fromUtf8(""))
        self.tabRes = QtGui.QWidget()
        self.tabRes.setObjectName(_fromUtf8("tabRes"))
        self.layoutWidget_6 = QtGui.QWidget(self.tabRes)
        self.layoutWidget_6.setGeometry(QtCore.QRect(20, 20, 374, 66))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget_6)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_11 = QtGui.QLabel(self.layoutWidget_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.leResName = QtGui.QLineEdit(self.layoutWidget_6)
        self.leResName.setMinimumSize(QtCore.QSize(231, 0))
        self.leResName.setObjectName(_fromUtf8("leResName"))
        self.gridLayout_2.addWidget(self.leResName, 0, 1, 1, 2)
        self.label_12 = QtGui.QLabel(self.layoutWidget_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 2)
        self.spbxResCeilPrio = QtGui.QSpinBox(self.layoutWidget_6)
        self.spbxResCeilPrio.setMinimumSize(QtCore.QSize(91, 0))
        self.spbxResCeilPrio.setObjectName(_fromUtf8("spbxResCeilPrio"))
        self.gridLayout_2.addWidget(self.spbxResCeilPrio, 1, 2, 1, 1)
        self.layoutWidget_13 = QtGui.QWidget(self.tabRes)
        self.layoutWidget_13.setGeometry(QtCore.QRect(230, 160, 31, 66))
        self.layoutWidget_13.setObjectName(_fromUtf8("layoutWidget_13"))
        self.gridLayout_9 = QtGui.QGridLayout(self.layoutWidget_13)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.btnResAdd = QtGui.QPushButton(self.layoutWidget_13)
        self.btnResAdd.setMaximumSize(QtCore.QSize(29, 16777215))
        self.btnResAdd.setObjectName(_fromUtf8("btnResAdd"))
        self.gridLayout_9.addWidget(self.btnResAdd, 0, 0, 1, 1)
        self.btnResRemove = QtGui.QPushButton(self.layoutWidget_13)
        self.btnResRemove.setMaximumSize(QtCore.QSize(29, 16777215))
        self.btnResRemove.setObjectName(_fromUtf8("btnResRemove"))
        self.gridLayout_9.addWidget(self.btnResRemove, 1, 0, 1, 1)
        self.trResAssignedTask = QtGui.QTreeWidget(self.tabRes)
        self.trResAssignedTask.setGeometry(QtCore.QRect(0, 100, 231, 251))
        self.trResAssignedTask.setObjectName(_fromUtf8("trResAssignedTask"))
        self.trResAvailableTask = QtGui.QTreeWidget(self.tabRes)
        self.trResAvailableTask.setGeometry(QtCore.QRect(260, 100, 211, 251))
        self.trResAvailableTask.setObjectName(_fromUtf8("trResAvailableTask"))
        self.trResAvailableTask.headerItem().setText(0, _fromUtf8("Available Task..."))
        self.tblGaInOsCfg.addTab(self.tabRes, _fromUtf8(""))
        self.tabInRes = QtGui.QWidget()
        self.tabInRes.setObjectName(_fromUtf8("tabInRes"))
        self.trInResAssignedTask = QtGui.QTreeWidget(self.tabInRes)
        self.trInResAssignedTask.setGeometry(QtCore.QRect(0, 100, 231, 251))
        self.trInResAssignedTask.setObjectName(_fromUtf8("trInResAssignedTask"))
        self.trInResAvailableTask = QtGui.QTreeWidget(self.tabInRes)
        self.trInResAvailableTask.setGeometry(QtCore.QRect(260, 100, 211, 251))
        self.trInResAvailableTask.setObjectName(_fromUtf8("trInResAvailableTask"))
        self.trInResAvailableTask.headerItem().setText(0, _fromUtf8("Available Task..."))
        self.layoutWidget_7 = QtGui.QWidget(self.tabInRes)
        self.layoutWidget_7.setGeometry(QtCore.QRect(230, 150, 31, 66))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_7)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.btnInResAdd = QtGui.QPushButton(self.layoutWidget_7)
        self.btnInResAdd.setMaximumSize(QtCore.QSize(29, 16777215))
        self.btnInResAdd.setObjectName(_fromUtf8("btnInResAdd"))
        self.gridLayout_7.addWidget(self.btnInResAdd, 0, 0, 1, 1)
        self.btnInResRemove = QtGui.QPushButton(self.layoutWidget_7)
        self.btnInResRemove.setMaximumSize(QtCore.QSize(29, 16777215))
        self.btnInResRemove.setObjectName(_fromUtf8("btnInResRemove"))
        self.gridLayout_7.addWidget(self.btnInResRemove, 1, 0, 1, 1)
        self.layoutWidget_8 = QtGui.QWidget(self.tabInRes)
        self.layoutWidget_8.setGeometry(QtCore.QRect(21, 21, 436, 66))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget_8)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_13 = QtGui.QLabel(self.layoutWidget_8)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.leInResName = QtGui.QLineEdit(self.layoutWidget_8)
        self.leInResName.setObjectName(_fromUtf8("leInResName"))
        self.gridLayout_3.addWidget(self.leInResName, 0, 1, 1, 2)
        self.label_14 = QtGui.QLabel(self.layoutWidget_8)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 2)
        self.spbxInResCeilPrio = QtGui.QSpinBox(self.layoutWidget_8)
        self.spbxInResCeilPrio.setMinimumSize(QtCore.QSize(91, 0))
        self.spbxInResCeilPrio.setMaximum(65535)
        self.spbxInResCeilPrio.setObjectName(_fromUtf8("spbxInResCeilPrio"))
        self.gridLayout_3.addWidget(self.spbxInResCeilPrio, 1, 2, 1, 1)
        self.tblGaInOsCfg.addTab(self.tabInRes, _fromUtf8(""))
        self.tabCnt = QtGui.QWidget()
        self.tabCnt.setObjectName(_fromUtf8("tabCnt"))
        self.layoutWidget_9 = QtGui.QWidget(self.tabCnt)
        self.layoutWidget_9.setGeometry(QtCore.QRect(20, 20, 420, 136))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget_9)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_15 = QtGui.QLabel(self.layoutWidget_9)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.leCntName = QtGui.QLineEdit(self.layoutWidget_9)
        self.leCntName.setMinimumSize(QtCore.QSize(231, 0))
        self.leCntName.setObjectName(_fromUtf8("leCntName"))
        self.gridLayout_4.addWidget(self.leCntName, 0, 1, 1, 3)
        self.label_16 = QtGui.QLabel(self.layoutWidget_9)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 2)
        self.spbxCntMaxAllowedValue = QtGui.QSpinBox(self.layoutWidget_9)
        self.spbxCntMaxAllowedValue.setMinimumSize(QtCore.QSize(91, 0))
        self.spbxCntMaxAllowedValue.setToolTip(_fromUtf8(""))
        self.spbxCntMaxAllowedValue.setMinimum(1)
        self.spbxCntMaxAllowedValue.setMaximum(65535)
        self.spbxCntMaxAllowedValue.setObjectName(_fromUtf8("spbxCntMaxAllowedValue"))
        self.gridLayout_4.addWidget(self.spbxCntMaxAllowedValue, 1, 2, 1, 2)
        self.label_17 = QtGui.QLabel(self.layoutWidget_9)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 2)
        self.spbxCntTickBase = QtGui.QSpinBox(self.layoutWidget_9)
        self.spbxCntTickBase.setMinimumSize(QtCore.QSize(91, 0))
        self.spbxCntTickBase.setToolTip(_fromUtf8(""))
        self.spbxCntTickBase.setMinimum(1)
        self.spbxCntTickBase.setMaximum(65535)
        self.spbxCntTickBase.setObjectName(_fromUtf8("spbxCntTickBase"))
        self.gridLayout_4.addWidget(self.spbxCntTickBase, 2, 2, 1, 2)
        self.label_18 = QtGui.QLabel(self.layoutWidget_9)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 3, 0, 1, 3)
        self.spbxCntMinCycle = QtGui.QSpinBox(self.layoutWidget_9)
        self.spbxCntMinCycle.setMinimumSize(QtCore.QSize(91, 0))
        self.spbxCntMinCycle.setToolTip(_fromUtf8(""))
        self.spbxCntMinCycle.setMinimum(1)
        self.spbxCntMinCycle.setMaximum(65535)
        self.spbxCntMinCycle.setObjectName(_fromUtf8("spbxCntMinCycle"))
        self.gridLayout_4.addWidget(self.spbxCntMinCycle, 3, 3, 1, 1)
        self.tblGaInOsCfg.addTab(self.tabCnt, _fromUtf8(""))
        self.tabAlm = QtGui.QWidget()
        self.tabAlm.setObjectName(_fromUtf8("tabAlm"))
        self.layoutWidget_14 = QtGui.QWidget(self.tabAlm)
        self.layoutWidget_14.setGeometry(QtCore.QRect(230, 270, 31, 66))
        self.layoutWidget_14.setObjectName(_fromUtf8("layoutWidget_14"))
        self.gridLayout_10 = QtGui.QGridLayout(self.layoutWidget_14)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.btnAlarmModeAdd = QtGui.QPushButton(self.layoutWidget_14)
        self.btnAlarmModeAdd.setMinimumSize(QtCore.QSize(29, 0))
        self.btnAlarmModeAdd.setMaximumSize(QtCore.QSize(29, 16777215))
        self.btnAlarmModeAdd.setObjectName(_fromUtf8("btnAlarmModeAdd"))
        self.gridLayout_10.addWidget(self.btnAlarmModeAdd, 0, 0, 1, 1)
        self.btnAlarmModeDel = QtGui.QPushButton(self.layoutWidget_14)
        self.btnAlarmModeDel.setMaximumSize(QtCore.QSize(29, 16777215))
        self.btnAlarmModeDel.setObjectName(_fromUtf8("btnAlarmModeDel"))
        self.gridLayout_10.addWidget(self.btnAlarmModeDel, 1, 0, 1, 1)
        self.trAlarmAppModeDst = QtGui.QTreeWidget(self.tabAlm)
        self.trAlarmAppModeDst.setGeometry(QtCore.QRect(10, 240, 211, 131))
        self.trAlarmAppModeDst.setObjectName(_fromUtf8("trAlarmAppModeDst"))
        self.trAlarmAppModeSrc = QtGui.QTreeWidget(self.tabAlm)
        self.trAlarmAppModeSrc.setGeometry(QtCore.QRect(270, 240, 201, 131))
        self.trAlarmAppModeSrc.setObjectName(_fromUtf8("trAlarmAppModeSrc"))
        self.trAlarmAppModeSrc.headerItem().setText(0, _fromUtf8("Available AppMode"))
        self.widget = QtGui.QWidget(self.tabAlm)
        self.widget.setGeometry(QtCore.QRect(10, 10, 451, 227))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_19 = QtGui.QLabel(self.widget)
        self.label_19.setEnabled(True)
        self.label_19.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_21.addWidget(self.label_19)
        self.leAlarmName = QtGui.QLineEdit(self.widget)
        self.leAlarmName.setEnabled(True)
        self.leAlarmName.setMinimumSize(QtCore.QSize(231, 0))
        self.leAlarmName.setObjectName(_fromUtf8("leAlarmName"))
        self.horizontalLayout_21.addWidget(self.leAlarmName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_24 = QtGui.QLabel(self.widget)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_22.addWidget(self.label_24)
        self.cmbxAlarmOwner = QtGui.QComboBox(self.widget)
        self.cmbxAlarmOwner.setMinimumSize(QtCore.QSize(231, 0))
        self.cmbxAlarmOwner.setToolTip(_fromUtf8(""))
        self.cmbxAlarmOwner.setObjectName(_fromUtf8("cmbxAlarmOwner"))
        self.horizontalLayout_22.addWidget(self.cmbxAlarmOwner)
        self.verticalLayout_3.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_20 = QtGui.QLabel(self.widget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_23.addWidget(self.label_20)
        self.cmbxAlarmType = QtGui.QComboBox(self.widget)
        self.cmbxAlarmType.setMinimumSize(QtCore.QSize(231, 0))
        self.cmbxAlarmType.setToolTip(_fromUtf8(""))
        self.cmbxAlarmType.setObjectName(_fromUtf8("cmbxAlarmType"))
        self.cmbxAlarmType.addItem(_fromUtf8(""))
        self.cmbxAlarmType.addItem(_fromUtf8(""))
        self.cmbxAlarmType.addItem(_fromUtf8(""))
        self.horizontalLayout_23.addWidget(self.cmbxAlarmType)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_21 = QtGui.QLabel(self.widget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_24.addWidget(self.label_21)
        self.leAlarmCbk = QtGui.QLineEdit(self.widget)
        self.leAlarmCbk.setEnabled(False)
        self.leAlarmCbk.setToolTip(_fromUtf8(""))
        self.leAlarmCbk.setText(_fromUtf8(""))
        self.leAlarmCbk.setObjectName(_fromUtf8("leAlarmCbk"))
        self.horizontalLayout_24.addWidget(self.leAlarmCbk)
        self.verticalLayout_3.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.lblAlarmTask = QtGui.QLabel(self.widget)
        self.lblAlarmTask.setObjectName(_fromUtf8("lblAlarmTask"))
        self.horizontalLayout_25.addWidget(self.lblAlarmTask)
        self.cmbxAlarmTask = QtGui.QComboBox(self.widget)
        self.cmbxAlarmTask.setMinimumSize(QtCore.QSize(231, 0))
        self.cmbxAlarmTask.setToolTip(_fromUtf8(""))
        self.cmbxAlarmTask.setObjectName(_fromUtf8("cmbxAlarmTask"))
        self.horizontalLayout_25.addWidget(self.cmbxAlarmTask)
        self.verticalLayout_3.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_23 = QtGui.QLabel(self.widget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_26.addWidget(self.label_23)
        self.cmbxAlarmEvent = QtGui.QComboBox(self.widget)
        self.cmbxAlarmEvent.setMinimumSize(QtCore.QSize(231, 0))
        self.cmbxAlarmEvent.setToolTip(_fromUtf8(""))
        self.cmbxAlarmEvent.setObjectName(_fromUtf8("cmbxAlarmEvent"))
        self.horizontalLayout_26.addWidget(self.cmbxAlarmEvent)
        self.verticalLayout_3.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.cbxAlarmAutostart = QtGui.QCheckBox(self.widget)
        self.cbxAlarmAutostart.setObjectName(_fromUtf8("cbxAlarmAutostart"))
        self.horizontalLayout_9.addWidget(self.cbxAlarmAutostart)
        self.spbxAlarmTime = QtGui.QSpinBox(self.widget)
        self.spbxAlarmTime.setMinimumSize(QtCore.QSize(125, 0))
        self.spbxAlarmTime.setMinimum(0)
        self.spbxAlarmTime.setMaximum(32767)
        self.spbxAlarmTime.setSingleStep(1)
        self.spbxAlarmTime.setProperty(_fromUtf8("value"), 100)
        self.spbxAlarmTime.setObjectName(_fromUtf8("spbxAlarmTime"))
        self.horizontalLayout_9.addWidget(self.spbxAlarmTime)
        self.label_28 = QtGui.QLabel(self.widget)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_9.addWidget(self.label_28)
        self.spbxAlarmCycleTime = QtGui.QSpinBox(self.widget)
        self.spbxAlarmCycleTime.setMinimumSize(QtCore.QSize(125, 0))
        self.spbxAlarmCycleTime.setMinimum(0)
        self.spbxAlarmCycleTime.setMaximum(32767)
        self.spbxAlarmCycleTime.setSingleStep(1)
        self.spbxAlarmCycleTime.setProperty(_fromUtf8("value"), 100)
        self.spbxAlarmCycleTime.setObjectName(_fromUtf8("spbxAlarmCycleTime"))
        self.horizontalLayout_9.addWidget(self.spbxAlarmCycleTime)
        self.label_30 = QtGui.QLabel(self.widget)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_9.addWidget(self.label_30)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.tblGaInOsCfg.addTab(self.tabAlm, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.btnCfgSchedEp = QtGui.QPushButton(self.tab)
        self.btnCfgSchedEp.setGeometry(QtCore.QRect(120, 250, 211, 23))
        self.btnCfgSchedEp.setObjectName(_fromUtf8("btnCfgSchedEp"))
        self.pteSchedTblInfo = QtGui.QPlainTextEdit(self.tab)
        self.pteSchedTblInfo.setGeometry(QtCore.QRect(10, 50, 451, 191))
        self.pteSchedTblInfo.setObjectName(_fromUtf8("pteSchedTblInfo"))
        self.layoutWidget5 = QtGui.QWidget(self.tab)
        self.layoutWidget5.setGeometry(QtCore.QRect(30, 10, 419, 27))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_27 = QtGui.QLabel(self.layoutWidget5)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_6.addWidget(self.label_27)
        self.leSchedTblName = QtGui.QLineEdit(self.layoutWidget5)
        self.leSchedTblName.setEnabled(True)
        self.leSchedTblName.setMinimumSize(QtCore.QSize(231, 0))
        self.leSchedTblName.setObjectName(_fromUtf8("leSchedTblName"))
        self.horizontalLayout_6.addWidget(self.leSchedTblName)
        self.tblGaInOsCfg.addTab(self.tab, _fromUtf8(""))
        self.tabEvent = QtGui.QWidget()
        self.tabEvent.setObjectName(_fromUtf8("tabEvent"))
        self.layoutWidget_12 = QtGui.QWidget(self.tabEvent)
        self.layoutWidget_12.setGeometry(QtCore.QRect(20, 21, 445, 66))
        self.layoutWidget_12.setObjectName(_fromUtf8("layoutWidget_12"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget_12)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_25 = QtGui.QLabel(self.layoutWidget_12)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_6.addWidget(self.label_25, 0, 0, 1, 1)
        self.leEventName = QtGui.QLineEdit(self.layoutWidget_12)
        self.leEventName.setMinimumSize(QtCore.QSize(331, 0))
        self.leEventName.setObjectName(_fromUtf8("leEventName"))
        self.gridLayout_6.addWidget(self.leEventName, 0, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.layoutWidget_12)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_6.addWidget(self.label_26, 1, 0, 1, 1)
        self.leEventMask = QtGui.QLineEdit(self.layoutWidget_12)
        self.leEventMask.setMinimumSize(QtCore.QSize(331, 0))
        self.leEventMask.setObjectName(_fromUtf8("leEventMask"))
        self.gridLayout_6.addWidget(self.leEventMask, 1, 1, 1, 1)
        self.tblGaInOsCfg.addTab(self.tabEvent, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget6 = QtGui.QWidget(self.tab_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 20, 456, 27))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_29 = QtGui.QLabel(self.layoutWidget6)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_15.addWidget(self.label_29)
        self.leAppModeName = QtGui.QLineEdit(self.layoutWidget6)
        self.leAppModeName.setMinimumSize(QtCore.QSize(331, 0))
        self.leAppModeName.setObjectName(_fromUtf8("leAppModeName"))
        self.horizontalLayout_15.addWidget(self.leAppModeName)
        self.tblGaInOsCfg.addTab(self.tab_2, _fromUtf8(""))
        self.trModule = QtGui.QTreeWidget(self.groupBox_2)
        self.trModule.setGeometry(QtCore.QRect(20, 40, 261, 381))
        self.trModule.setObjectName(_fromUtf8("trModule"))
        item_0 = QtGui.QTreeWidgetItem(self.trModule)
        item_0 = QtGui.QTreeWidgetItem(self.trModule)
        item_0 = QtGui.QTreeWidgetItem(self.trModule)
        item_0 = QtGui.QTreeWidgetItem(self.trModule)
        item_0 = QtGui.QTreeWidgetItem(self.trModule)
        item_0 = QtGui.QTreeWidgetItem(self.trModule)
        self.layoutWidget7 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(290, 70, 151, 62))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.btnAdd = QtGui.QPushButton(self.layoutWidget7)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.verticalLayout.addWidget(self.btnAdd)
        self.btnDel = QtGui.QPushButton(self.layoutWidget7)
        self.btnDel.setObjectName(_fromUtf8("btnDel"))
        self.verticalLayout.addWidget(self.btnDel)

        self.retranslateUi(cd_os)
        self.tblGaInOsCfg.setCurrentIndex(4)
        self.cmbxTskType.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(cd_os)

    def retranslateUi(self, cd_os):
        cd_os.setWindowTitle(QtGui.QApplication.translate("cd_os", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("cd_os", "GaInOS General Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("cd_os", "Check Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxStatus.setItemText(0, QtGui.QApplication.translate("cd_os", "STANDARD", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxStatus.setItemText(1, QtGui.QApplication.translate("cd_os", "EXTENDED", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("cd_os", "Schedule Policy:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSchedPolicy.setItemText(0, QtGui.QApplication.translate("cd_os", "FULL_PREEMPTIVE_SCHEDULE", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSchedPolicy.setItemText(1, QtGui.QApplication.translate("cd_os", "MIXED_PREEMPTIVE_SCHEDULE", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxSchedPolicy.setItemText(2, QtGui.QApplication.translate("cd_os", "NONE_PREEMPTIVE_SCHEDULE", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxTkExtend.setToolTip(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">when on,the tk extend api(SleepTask &amp; WakeUpTask) can be used.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">But really I do not advise you to turn it on.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">I just implement it for fun but it\'s ugly and may ruin the wonderful features of OSEK os.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">As I have implemented it, I don\'t want to remove it,So use this switch to turn it off.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxTkExtend.setText(QtGui.QApplication.translate("cd_os", "Tk Extend API", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxOsStartUpHook.setText(QtGui.QApplication.translate("cd_os", "os start up hook", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxOsShutDownHook.setText(QtGui.QApplication.translate("cd_os", "os shut down hook", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxPreTaskHook.setText(QtGui.QApplication.translate("cd_os", "pre-task hook", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxPostTaskHook.setText(QtGui.QApplication.translate("cd_os", "post-task hook", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxOsErrorHook.setText(QtGui.QApplication.translate("cd_os", "os error hook", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("cd_os", "MAX_IPL:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("cd_os", "MAX_PRI:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("cd_os", "OS Class:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxOSConfCls.setItemText(0, QtGui.QApplication.translate("cd_os", "BCC1", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxOSConfCls.setItemText(1, QtGui.QApplication.translate("cd_os", "BCC2", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxOSConfCls.setItemText(2, QtGui.QApplication.translate("cd_os", "ECC1", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxOSConfCls.setItemText(3, QtGui.QApplication.translate("cd_os", "ECC2", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxTskStkOverflowCheck.setText(QtGui.QApplication.translate("cd_os", "task stack overflow check", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("cd_os", "System Stack Size(byte):", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxShareSystemStack.setToolTip(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">only supported when os class is BCC.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxShareSystemStack.setText(QtGui.QApplication.translate("cd_os", "task/ISR share the system stack", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("cd_os", "GaInOS-TK Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.tblGaInOsCfg.setWhatsThis(QtGui.QApplication.translate("cd_os", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.trTaskAppModeDst.headerItem().setText(0, QtGui.QApplication.translate("cd_os", "Assigned AppMode", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTaskModeAdd.setText(QtGui.QApplication.translate("cd_os", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTaskModeDel.setText(QtGui.QApplication.translate("cd_os", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Task Name:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.leTskName.setText(QtGui.QApplication.translate("cd_os", "vTask", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Task Stack Size(byte):</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Task Type:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxTskType.setToolTip(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Whether a task is extended or basic is up to whether an event has been added or not!</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxTskType.setItemText(0, QtGui.QApplication.translate("cd_os", "BASIC_TASK", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxTskType.setItemText(1, QtGui.QApplication.translate("cd_os", "EXTEND_TASK", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("cd_os", "Task Priority:", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxTskPrio.setToolTip(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0 is the lowest priority,the configured MAX_PRI is the highest.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("cd_os", "Task Max Activate Count:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxTskPreemtable.setText(QtGui.QApplication.translate("cd_os", "Task Preemtable", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxTaskAutostart.setText(QtGui.QApplication.translate("cd_os", "Task Autostart", None, QtGui.QApplication.UnicodeUTF8))
        self.tblGaInOsCfg.setTabText(self.tblGaInOsCfg.indexOf(self.tabTask), QtGui.QApplication.translate("cd_os", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Resource Name:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.leResName.setText(QtGui.QApplication.translate("cd_os", "vRes1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Resource Ceiling Priority:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxResCeilPrio.setToolTip(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0 is the lowest priority,the configured MAX_PRI is the highest.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnResAdd.setText(QtGui.QApplication.translate("cd_os", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.btnResRemove.setText(QtGui.QApplication.translate("cd_os", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.trResAssignedTask.setToolTip(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">For normal resource, each task can get it, but you should make sure that the ceiling priority should be higher than all the tasks that will acquire this normal resource.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">So you can ignore this config,this just help you to remember, don\'t expect this tool will help you to resolve the ceiling priority automatically, you should do this!</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.trResAssignedTask.headerItem().setText(0, QtGui.QApplication.translate("cd_os", "Assigned To Task...", None, QtGui.QApplication.UnicodeUTF8))
        self.tblGaInOsCfg.setTabText(self.tblGaInOsCfg.indexOf(self.tabRes), QtGui.QApplication.translate("cd_os", "Resource", None, QtGui.QApplication.UnicodeUTF8))
        self.trInResAssignedTask.setToolTip(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Internal Resource is really special,only the task assigned with this internal resource can get it.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Note that each task can only has one internal resource,so be carefull. This tool has no validation function.So configure it right.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.trInResAssignedTask.headerItem().setText(0, QtGui.QApplication.translate("cd_os", "Assigned To Task...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnInResAdd.setText(QtGui.QApplication.translate("cd_os", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.btnInResRemove.setText(QtGui.QApplication.translate("cd_os", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Internal Resource Name:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.leInResName.setText(QtGui.QApplication.translate("cd_os", "vInRes1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Internal Resource Ceiling Priority:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxInResCeilPrio.setToolTip(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0 is the lowest priority,the configured MAX_PRI is the highest.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tblGaInOsCfg.setTabText(self.tblGaInOsCfg.indexOf(self.tabInRes), QtGui.QApplication.translate("cd_os", "Internal Resource", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Counter Name:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.leCntName.setText(QtGui.QApplication.translate("cd_os", "vCnt1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Counter Max Allowed Value:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Counter Ticks Per Base:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Counter Minimum Cycle:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tblGaInOsCfg.setTabText(self.tblGaInOsCfg.indexOf(self.tabCnt), QtGui.QApplication.translate("cd_os", "Counter", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAlarmModeAdd.setText(QtGui.QApplication.translate("cd_os", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAlarmModeDel.setText(QtGui.QApplication.translate("cd_os", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.trAlarmAppModeDst.headerItem().setText(0, QtGui.QApplication.translate("cd_os", "Assigned AppMode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Alarm Name:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.leAlarmName.setText(QtGui.QApplication.translate("cd_os", "vAlarm1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Alarm Owner:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Alarm Type:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxAlarmType.setItemText(0, QtGui.QApplication.translate("cd_os", "callback", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxAlarmType.setItemText(1, QtGui.QApplication.translate("cd_os", "task", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbxAlarmType.setItemText(2, QtGui.QApplication.translate("cd_os", "event", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Alarm Callback Name:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAlarmTask.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Alarm Event Task:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Alarm Set Event:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxAlarmAutostart.setToolTip(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">is Alarm autostartable</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxAlarmAutostart.setText(QtGui.QApplication.translate("cd_os", "SetRelAlarm(", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxAlarmTime.setToolTip(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Increment &lt;that is alarm start time&gt;</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">,</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.spbxAlarmCycleTime.setToolTip(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Cyclic Time</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">);</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tblGaInOsCfg.setTabText(self.tblGaInOsCfg.indexOf(self.tabAlm), QtGui.QApplication.translate("cd_os", "Alarm", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCfgSchedEp.setText(QtGui.QApplication.translate("cd_os", "Configure Expiry Point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Schedule Table Name:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.leSchedTblName.setText(QtGui.QApplication.translate("cd_os", "vSchedTbl", None, QtGui.QApplication.UnicodeUTF8))
        self.tblGaInOsCfg.setTabText(self.tblGaInOsCfg.indexOf(self.tab), QtGui.QApplication.translate("cd_os", "Schedule Table", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p><span style=\" font-size:12pt;\">Event Name:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("cd_os", "<html><head/><body><p>Event Mask:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tblGaInOsCfg.setTabText(self.tblGaInOsCfg.indexOf(self.tabEvent), QtGui.QApplication.translate("cd_os", "Event", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("cd_os", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">AppMode Name:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tblGaInOsCfg.setTabText(self.tblGaInOsCfg.indexOf(self.tab_2), QtGui.QApplication.translate("cd_os", "AppMode", None, QtGui.QApplication.UnicodeUTF8))
        self.trModule.headerItem().setText(0, QtGui.QApplication.translate("cd_os", "OSEK OS", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.trModule.isSortingEnabled()
        self.trModule.setSortingEnabled(False)
        self.trModule.topLevelItem(0).setText(0, QtGui.QApplication.translate("cd_os", "AppMode", None, QtGui.QApplication.UnicodeUTF8))
        self.trModule.topLevelItem(1).setText(0, QtGui.QApplication.translate("cd_os", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.trModule.topLevelItem(2).setText(0, QtGui.QApplication.translate("cd_os", "Resource", None, QtGui.QApplication.UnicodeUTF8))
        self.trModule.topLevelItem(3).setText(0, QtGui.QApplication.translate("cd_os", "Counter", None, QtGui.QApplication.UnicodeUTF8))
        self.trModule.topLevelItem(4).setText(0, QtGui.QApplication.translate("cd_os", "Alarm", None, QtGui.QApplication.UnicodeUTF8))
        self.trModule.topLevelItem(5).setText(0, QtGui.QApplication.translate("cd_os", "Internal Resource", None, QtGui.QApplication.UnicodeUTF8))
        self.trModule.setSortingEnabled(__sortingEnabled)
        self.btnAdd.setText(QtGui.QApplication.translate("cd_os", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDel.setText(QtGui.QApplication.translate("cd_os", "Delete", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    cd_os = QtGui.QDialog()
    ui = Ui_cd_os()
    ui.setupUi(cd_os)
    cd_os.show()
    sys.exit(app.exec_())

